.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-MV" "1" "10/03/2006" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-mv \- Move or rename a file, directory or symlink
.SH "SYNOPSIS"
\fIgit\-mv\fR <options>\&... <args>\&...
.sp
.SH "DESCRIPTION"
This script is used to move or rename a file, directory or symlink.
.sp
.sp
.nf
git\-mv [\-f] [\-n] <source> <destination>
git\-mv [\-f] [\-n] [\-k] <source> ... <destination directory>
.fi
In the first form, it renames <source>, which must exist and be either a file, symlink or directory, to <destination>. In the second form, the last argument has to be an existing directory; the given sources will be moved into this directory.
.sp
The index is updated after successful completion, but the change must still be committed.
.sp
.SH "OPTIONS"
.TP
\-f
Force renaming or moving of a file even if the target exists
.TP
\-k
Skip move or rename actions which would lead to an error condition. An error happens when a source is neither existing nor controlled by GIT, or when it would overwrite an existing file unless
\fI\-f\fR
is given.
.TP
\-n
Do nothing; only show what would happen
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl.org> Rewritten by Ryan Anderson <ryan@michonline.com> Move functionality added by Josef Weidendorfer <Josef.Weidendorfer@gmx.de>
.sp
.SH "DOCUMENTATION"
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger.kernel.org>.
.sp
.SH "GIT"
Part of the \fBgit\fR(7) suite
.sp
