.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-VERIFY\-PACK" "1" "10/03/2006" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-verify\-pack \- Validate packed git archive files
.SH "SYNOPSIS"
\fIgit\-verify\-pack\fR [\-v] [\-\-] <pack>.idx \&...
.sp
.SH "DESCRIPTION"
Reads given idx file for packed git archive created with git\-pack\-objects command and verifies idx file and the corresponding pack file.
.sp
.SH "OPTIONS"
.TP
<pack>.idx \&...
The idx files to verify.
.TP
\-v
After verifying the pack, show list of objects contained in the pack.
.TP
\-\-
Do not interpret any more arguments as options.
.SH "OUTPUT FORMAT"
When specifying the \-v option the format used is:
.sp
.sp
.nf
SHA1 type size offset\-in\-packfile
.fi
for objects that are not deltified in the pack, and
.sp
.sp
.nf
SHA1 type size offset\-in\-packfile depth base\-SHA1
.fi
for objects that are deltified.
.sp
.SH "AUTHOR"
Written by Junio C Hamano <junkio@cox.net>
.sp
.SH "DOCUMENTATION"
Documentation by Junio C Hamano
.sp
.SH "GIT"
Part of the \fBgit\fR(7) suite
.sp
