.\"     Title: git-write-tree
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 08/26/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.4.1.207.g68ea
.\"
.TH "GIT\-WRITE\-TREE" "1" "08/26/2009" "Git 1\.6\.4\.1\.207\.g68ea" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-write-tree - Create a tree object from the current index
.SH "SYNOPSIS"
\fIgit write\-tree\fR [\-\-missing\-ok] [\-\-prefix=<prefix>/]
.sp
.SH "DESCRIPTION"
Creates a tree object using the current index\. The name of the new tree object is printed to standard output\.
.sp
The index must be in a fully merged state\.
.sp
Conceptually, \fIgit\-write\-tree\fR sync()s the current index contents into a set of tree files\. In order to have that match what is actually in your directory right now, you need to have done a \fIgit\-update\-index\fR phase before you did the \fIgit\-write\-tree\fR\.
.sp
.SH "OPTIONS"
.PP
\-\-missing\-ok
.RS 4
Normally
\fIgit\-write\-tree\fR
ensures that the objects referenced by the directory exist in the object database\. This option disables this check\.
.RE
.PP
\-\-prefix=<prefix>/
.RS 4
Writes a tree object that represents a subdirectory
<prefix>\. This can be used to write the tree object for a subproject that is in the named subdirectory\.
.RE
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl\.org>
.sp
.SH "DOCUMENTATION"
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger\.kernel\.org>\.
.sp
.SH "GIT"
Part of the \fBgit\fR(1) suite
.sp
