.\"     Title: git-notes
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 02/06/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.1.2.390.gba743
.\"
.TH "GIT\-NOTES" "1" "02/06/2009" "Git 1\.6\.1\.2\.390\.gba743" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-notes - Add/inspect commit notes
.SH "SYNOPSIS"
.sp
.RS 4
.nf
\fIgit\-notes\fR (edit | show) [commit]
.fi
.RE
.SH "DESCRIPTION"
This command allows you to add notes to commit messages, without changing the commit\. To discern these notes from the message stored in the commit object, the notes are indented like the message, after an unindented line saying "Notes:"\.

To disable commit notes, you have to set the config variable core\.notesRef to the empty string\. Alternatively, you can set it to a different ref, something like "refs/notes/bugzilla"\. This setting can be overridden by the environment variable "GIT_NOTES_REF"\.
.SH "SUBCOMMANDS"
.PP
edit
.RS 4
Edit the notes for a given commit (defaults to HEAD)\.
.RE
.PP
show
.RS 4
Show the notes for a given commit (defaults to HEAD)\.
.RE
.SH "AUTHOR"
Written by Johannes Schindelin <johannes\.schindelin@gmx\.de>
.SH "DOCUMENTATION"
Documentation by Johannes Schindelin
.SH "GIT"
Part of the git\fI7\fR\&[1] suite
.SH "NOTES"
.IP " 1." 4
7
.RS 4
\%git
.RE
