'\" t
.\"     Title: git-relink
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/26/2014
.\"    Manual: Git Manual
.\"    Source: Git
.\"  Language: English
.\"
.TH "GIT\-RELINK" "1" "11/26/2014" "Git" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-relink \- Hardlink common objects in local repositories
.SH "SYNOPSIS"
.sp
.nf
\fIgit relink\fR [\-\-safe] <dir>\&... <master_dir>
.fi
.sp
.SH "DESCRIPTION"
.sp
This will scan 1 or more object repositories and look for objects in common with a master repository\&. Objects not already hardlinked to the master repository will be replaced with a hardlink to the master repository\&.
.SH "OPTIONS"
.PP
\-\-safe
.RS 4
Stops if two objects with the same hash exist but have different sizes\&. Default is to warn and continue\&.
.RE
.PP
<dir>
.RS 4
Directories containing a \&.git/objects/ subdirectory\&.
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
