'\" t
.\"     Title: git-status
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 04/24/2010
.\"    Manual: Git Manual
.\"    Source: Git 1.7.1
.\"  Language: English
.\"
.TH "GIT\-STATUS" "1" "04/24/2010" "Git 1\&.7\&.1" "Git Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-status \- Show the working tree status
.SH "SYNOPSIS"
.sp
\fIgit status\fR [<options>\&...] [\-\-] [<pathspec>\&...]
.SH "DESCRIPTION"
.sp
Displays paths that have differences between the index file and the current HEAD commit, paths that have differences between the working tree and the index file, and paths in the working tree that are not tracked by git (and are not ignored by \fBgitignore\fR(5))\&. The first are what you _would_ commit by running git commit; the second and third are what you _could_ commit by running \fIgit add\fR before running git commit\&.
.SH "OPTIONS"
.PP
\-s, \-\-short
.RS 4
Give the output in the short\-format\&.
.RE
.PP
\-\-porcelain
.RS 4
Give the output in a stable, easy\-to\-parse format for scripts\&. Currently this is identical to \-\-short output, but is guaranteed not to change in the future, making it safe for scripts\&.
.RE
.PP
\-u[<mode>], \-\-untracked\-files[=<mode>]
.RS 4
Show untracked files (Default:
\fIall\fR)\&.
.sp
The mode parameter is optional, and is used to specify the handling of untracked files\&. The possible options are:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIno\fR
\- Show no untracked files
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fInormal\fR
\- Shows untracked files and directories
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIall\fR
\- Also shows individual files in untracked directories\&.
.RE
.RS 4
See
\fBgit-config\fR(1)
for configuration variable used to change the default for when the option is not specified\&.
.RE
.PP
\-z
.RS 4
Terminate entries with NUL, instead of LF\&. This implies the
\-\-porcelain
output format if no other format is given\&.
.RE
.SH "OUTPUT"
.sp
The output from this command is designed to be used as a commit template comment, and all the output lines are prefixed with \fI#\fR\&. The default, long format, is designed to be human readable, verbose and descriptive\&. They are subject to change in any time\&.
.sp
The paths mentioned in the output, unlike many other git commands, are made relative to the current directory if you are working in a subdirectory (this is on purpose, to help cutting and pasting)\&. See the status\&.relativePaths config option below\&.
.sp
In short\-format, the status of each path is shown as
.sp
.if n \{\
.RS 4
.\}
.nf
XY PATH1 \-> PATH2
.fi
.if n \{\
.RE
.\}
.sp
where PATH1 is the path in the HEAD, and \-> PATH2 part is shown only when PATH1 corresponds to a different path in the index/worktree (i\&.e\&. the file is renamed)\&. The \fIXY\fR is a two\-letter status code\&.
.sp
The fields (including the \->) are separated from each other by a single space\&. If a filename contains whitespace or other nonprintable characters, that field will be quoted in the manner of a C string literal: surrounded by ASCII double quote (34) characters, and with interior special characters backslash\-escaped\&.
.sp
For paths with merge conflicts, X and \fIY\fR show the modification states of each side of the merge\&. For paths that do not have merge conflicts, X shows the status of the index, and Y shows the status of the work tree\&. For untracked paths, XY are ??\&. Other status codes can be interpreted as follows:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fI \fR
= unmodified
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIM\fR
= modified
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIA\fR
= added
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fID\fR
= deleted
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIR\fR
= renamed
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIC\fR
= copied
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}

\fIU\fR
= updated but unmerged
.RE
.sp
Ignored files are not listed\&.
.sp
.if n \{\
.RS 4
.\}
.nf
X          Y     Meaning
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
          [MD]   not updated
M        [ MD]   updated in index
A        [ MD]   added to index
D         [ M]   deleted from index
R        [ MD]   renamed in index
C        [ MD]   copied in index
[MARC]           index and work tree matches
[ MARC]     M    work tree changed since index
[ MARC]     D    deleted in work tree
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
D           D    unmerged, both deleted
A           U    unmerged, added by us
U           D    unmerged, deleted by them
U           A    unmerged, added by them
D           U    unmerged, deleted by us
A           A    unmerged, both added
U           U    unmerged, both modified
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
?           ?    untracked
\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-
.fi
.if n \{\
.RE
.\}
.sp
There is an alternate \-z format recommended for machine parsing\&. In that format, the status field is the same, but some other things change\&. First, the \fI\->\fR is omitted from rename entries and the field order is reversed (e\&.g \fIfrom \-> to\fR becomes \fIto from\fR)\&. Second, a NUL (ASCII 0) follows each filename, replacing space as a field separator and the terminating newline (but a space still separates the status field from the first filename)\&. Third, filenames containing special characters are not specially formatted; no quoting or backslash\-escaping is performed\&.
.SH "CONFIGURATION"
.sp
The command honors color\&.status (or status\&.color \(em they mean the same thing and the latter is kept for backward compatibility) and color\&.status\&.<slot> configuration variables to colorize its output\&.
.sp
If the config variable status\&.relativePaths is set to false, then all paths shown are relative to the repository root, not to the current directory\&.
.sp
If status\&.submodulesummary is set to a non zero number or true (identical to \-1 or an unlimited number), the submodule summary will be enabled for the long format and a summary of commits for modified submodules will be shown (see \-\-summary\-limit option of \fBgit-submodule\fR(1))\&.
.SH "SEE ALSO"
.sp
\fBgitignore\fR(5)
.SH "AUTHOR"
.sp
Written by Junio C Hamano <gitster@pobox\&.com>\&.
.SH "DOCUMENTATION"
.sp
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger\&.kernel\&.org>\&.
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
