.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-PRUNE" "1" "01/07/2008" "Git 1.5.4.rc2.60.gb2e62" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-prune \- Prune all unreachable objects from the object database
.SH "SYNOPSIS"
\fIgit\-prune\fR [\-n] [\-\-expire <expire>] [\-\-] [<head>\&...]
.SH "DESCRIPTION"
This runs git\-fsck \-\-unreachable using all the refs available in $GIT_DIR/refs, optionally with additional set of objects specified on the command line, and prunes all objects unreachable from any of these head objects from the object database. In addition, it prunes the unpacked objects that are also found in packs by running git prune\-packed.
.SH "OPTIONS"
.TP
\-n
Do not remove anything; just report what it would remove.
.TP
\-\-
Do not interpret any more arguments as options.
.TP
\-\-expire <time>
Only expire loose objects older than <time>.
.TP
<head>\&...
In addition to objects reachable from any of our references, keep objects reachable from listed <head>s.
.SH "EXAMPLE"
To prune objects not used by your repository nor another that borrows from your repository via its .git/objects/info/alternates:
.sp
.nf
.ft C
$ git prune $(cd ../another && $(git\-rev\-parse \-\-all))
.ft

.fi
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl.org>
.SH "DOCUMENTATION"
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

