.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-MERGE\-TREE" "1" "06/08/2007" "Git 1.5.2.1.144.gabc40" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-merge\-tree \- Show three\-way merge without touching index
.SH "SYNOPSIS"
\fIgit\-merge\-tree\fR <base\-tree> <branch1> <branch2>
.SH "DESCRIPTION"
Reads three treeish, and output trivial merge results and conflicting stages to the standard output. This is similar to what three\-way read\-tree \-m does, but instead of storing the results in the index, the command outputs the entries to the standard output.

This is meant to be used by higher level scripts to compute merge results outside index, and stuff the results back into the index. For this reason, the output from the command omits entries that match <branch1> tree.
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl.org>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano and the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

