.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-MKTAG" "1" "06/08/2007" "Git 1.5.2.1.144.gabc40" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-mktag \- Creates a tag object
.SH "SYNOPSIS"
\fIgit\-mktag\fR < signature_file
.SH "DESCRIPTION"
Reads a tag contents on standard input and creates a tag object that can also be used to sign other objects.

The output is the new tag's <object> identifier.
.SH "TAG FORMAT"
A tag signature file has a very simple fixed format: three lines of
.sp
.nf
object <sha1>
type <typename>
tag <tagname>
.fi
followed by some \fIoptional\fR free\-form signature that git itself doesn't care about, but that can be verified with gpg or similar.

The size of the full object is artificially limited to 8kB. (Just because I'm a lazy bastard, and if you can't fit a signature in that size, you're doing something wrong)
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl.org>
.SH "DOCUMENTATION"
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

