.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-HASH\-OBJECT" "1" "01/19/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-hash\-object \- Compute object ID and optionally creates a blob from a file
.SH "SYNOPSIS"
\fIgit\-hash\-object\fR [\-t <type>] [\-w] [\-\-stdin] [\-\-] <file>\&...
.SH "DESCRIPTION"
Computes the object ID value for an object with specified type with the contents of the named file (which can be outside of the work tree), and optionally writes the resulting object into the object database. Reports its object ID to its standard output. This is used by "git\-cvsimport" to update the index without modifying files in the work tree. When <type> is not specified, it defaults to "blob".
.SH "OPTIONS"
.TP
\-t <type>
Specify the type (default: "blob").
.TP
\-w
Actually write the object into the object database.
.TP
\-\-stdin
Read the object from standard input instead of from a file.
.SH "AUTHOR"
Written by Junio C Hamano <junkio@cox.net>
.SH "DOCUMENTATION"
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

