.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-TAG" "1" "10/03/2006" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-tag \- Create a tag object signed with GPG
.SH "SYNOPSIS"
.sp
.nf
\fIgit\-tag\fR [\-a | \-s | \-u <key\-id>] [\-f | \-d] [\-m <msg>] <name> [<head>]
\fIgit\-tag\fR \-l [<pattern>]
.fi
.SH "DESCRIPTION"
Adds a \fItag\fR reference in .git/refs/tags/
.sp
Unless \-f is given, the tag must not yet exist in .git/refs/tags/ directory.
.sp
If one of \-a, \-s, or \-u <key\-id> is passed, the command creates a \fItag\fR object, and requires the tag message. Unless \-m <msg> is given, an editor is started for the user to type in the tag message.
.sp
Otherwise just the SHA1 object name of the commit object is written (i.e. a lightweight tag).
.sp
A GnuPG signed tag object will be created when \-s or \-u <key\-id> is used. When \-u <key\-id> is not used, the committer identity for the current user is used to find the GnuPG key for signing.
.sp
\-d <tag> deletes the tag.
.sp
\-l <pattern> lists tags that match the given pattern (or all if no pattern is given).
.sp
.SH "OPTIONS"
.TP
\-a
Make an unsigned, annotated tag object
.TP
\-s
Make a GPG\-signed tag, using the default e\-mail address's key
.TP
\-u <key\-id>
Make a GPG\-signed tag, using the given key
.TP
\-f
Replace an existing tag with the given name (instead of failing)
.TP
\-d
Delete an existing tag with the given name
.TP
\-l <pattern>
List tags that match the given pattern (or all if no pattern is given).
.TP
\-m <msg>
Use the given tag message (instead of prompting)
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl.org>, Junio C Hamano <junkio@cox.net> and Chris Wright <chrisw@osdl.org>.
.sp
.SH "DOCUMENTATION"
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger.kernel.org>.
.sp
.SH "GIT"
Part of the \fBgit\fR(7) suite
.sp
