.\"     Title: git-get-tar-commit-id
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 07/01/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.2.rc0.64.ge9cc0
.\"
.TH "GIT\-GET\-TAR\-COMMI" "1" "07/01/2009" "Git 1\.6\.2\.rc0\.64\.ge9cc0" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-get-tar-commit-id - Extract commit ID from an archive created using git-archive
.SH "SYNOPSIS"
\fIgit get\-tar\-commit\-id\fR < <tarfile>
.sp
.SH "DESCRIPTION"
Acts as a filter, extracting the commit ID stored in archives created by \fIgit\-archive\fR\. It reads only the first 1024 bytes of input, thus its runtime is not influenced by the size of <tarfile> very much\.
.sp
If no commit ID is found, \fIgit\-get\-tar\-commit\-id\fR quietly exists with a return code of 1\. This can happen if <tarfile> had not been created using \fIgit\-archive\fR or if the first parameter of \fIgit\-archive\fR had been a tree ID instead of a commit ID or tag\.
.sp
.SH "AUTHOR"
Written by Rene Scharfe <rene\.scharfe@lsrfire\.ath\.cx>
.sp
.SH "DOCUMENTATION"
Documentation by Junio C Hamano and the git\-list <git@vger\.kernel\.org>\.
.sp
.SH "GIT"
Part of the \fBgit\fR(1) suite
.sp
