.\"     Title: git-unpack-objects
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 10/31/2008
.\"    Manual: Git Manual
.\"    Source: Git 1.6.0.2.287.g3791f
.\"
.TH "GIT\-UNPACK\-OBJECTS" "1" "10/31/2008" "Git 1\.6\.0\.2\.287\.g3791f" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-unpack-objects - Unpack objects from a packed archive
.SH "SYNOPSIS"
\fIgit unpack\-objects\fR [\-n] [\-q] [\-r] [\-\-strict] <pack\-file
.SH "DESCRIPTION"
Read a packed archive (\.pack) from the standard input, expanding the objects contained within and writing them into the repository in "loose" (one object per file) format\.

Objects that already exist in the repository will \fBnot\fR be unpacked from the pack\-file\. Therefore, nothing will be unpacked if you use this command on a pack\-file that exists within the target repository\.

See \fBgit-repack\fR(1) for options to generate new packs and replace existing ones\.
.SH "OPTIONS"
.PP
\-n
.RS 4
Dry run\. Check the pack file without actually unpacking the objects\.
.RE
.PP
\-q
.RS 4
The command usually shows percentage progress\. This flag suppresses it\.
.RE
.PP
\-r
.RS 4
When unpacking a corrupt packfile, the command dies at the first corruption\. This flag tells it to keep going and make the best effort to recover as many objects as possible\.
.RE
.PP
\-\-strict
.RS 4
Don\'t write objects with broken content or links\.
.RE
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl\.org>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano
.SH "GIT"
Part of the \fBgit\fR(1) suite

