.\"     Title: git-shortlog
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 02/14/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.2.rc0.64.ge9cc0
.\"
.TH "GIT\-SHORTLOG" "1" "02/14/2009" "Git 1\.6\.2\.rc0\.64\.ge9cc0" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-shortlog - Summarize 'git-log' output
.SH "SYNOPSIS"
.sp
.RS 4
.nf
git log \-\-pretty=short | \fIgit shortlog\fR [\-h] [\-n] [\-s] [\-e] [\-w]
git shortlog [\-n|\-\-numbered] [\-s|\-\-summary] [\-e|\-\-email] [\-w[<width>[,<indent1>[,<indent2>]]]] [<committish>\&...]
.fi
.RE
.SH "DESCRIPTION"
Summarizes \fIgit\-log\fR output in a format suitable for inclusion in release announcements\. Each commit will be grouped by author and the first line of the commit message will be shown\.

Additionally, "[PATCH]" will be stripped from the commit description\.
.SH "OPTIONS"
.PP
\-h, \-\-help
.RS 4
Print a short usage message and exit\.
.RE
.PP
\-n, \-\-numbered
.RS 4
Sort output according to the number of commits per author instead of author alphabetic order\.
.RE
.PP
\-s, \-\-summary
.RS 4
Suppress commit description and provide a commit count summary only\.
.RE
.PP
\-e, \-\-email
.RS 4
Show the email address of each author\.
.RE
.PP
\-w[<width>[,<indent1>[,<indent2>]]]
.RS 4
Linewrap the output by wrapping each line at width\. The first line of each entry is indented by indent1 spaces, and the second and subsequent lines are indented by indent2 spaces\. width, indent1, and indent2 default to 76, 6 and 9 respectively\.
.RE
.SH "FILES"
If a file \.mailmap exists at the toplevel of the repository, it is used to map an author email address to a canonical real name\. This can be used to coalesce together commits by the same person where their name was spelled differently (whether with the same email address or not)\.

Each line in the file consists, in this order, of the canonical real name of an author, whitespace, and an email address (enclosed by \fI<\fR and \fI>\fR) to map to the name\. Use hash \fI#\fR for comments, either on their own line, or after the email address\.

A canonical name may appear in more than one line, associated with different email addresses, but it doesn\'t make sense for a given address to appear more than once (if that happens, a later line overrides the earlier ones)\.

So, for example, if your history contains commits by two authors, Jane and Joe, whose names appear in the repository under several forms:

.sp
.RS 4
.nf

\.ft C
Joe Developer <joe@example\.com>
Joe R\. Developer <joe@example\.com>
Jane Doe <jane@example\.com>
Jane Doe <jane@laptop\.(none)>
Jane D\. <jane@desktop\.(none)>
\.ft

.fi
.RE
Then, supposing Joe wants his middle name initial used, and Jane prefers her family name fully spelled out, a proper \.mailmap file would look like:

.sp
.RS 4
.nf

\.ft C
# Note how we don\'t need an entry for <jane@laptop\.(none)>, because the
# real name of that author is correct already, and coalesced directly\.
Jane Doe <jane@desktop\.(none)>
Joe R\. Developer <joe@example\.com>
\.ft

.fi
.RE
.SH "AUTHOR"
Written by Jeff Garzik <jgarzik@pobox\.com>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano\.
.SH "GIT"
Part of the \fBgit\fR(1) suite

