.\"     Title: git-revert
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 07/22/2008
.\"    Manual: Git Manual
.\"    Source: Git 1.6.0.rc0.14.g95f8
.\"
.TH "GIT\-REVERT" "1" "07/22/2008" "Git 1\.6\.0\.rc0\.14\.g95f8" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-revert - Revert an existing commit
.SH "SYNOPSIS"
\fIgit revert\fR [\-\-edit | \-\-no\-edit] [\-n] [\-m parent\-number] [\-s] <commit>
.SH "DESCRIPTION"
Given one existing commit, revert the change the patch introduces, and record a new commit that records it\. This requires your working tree to be clean (no modifications from the HEAD commit)\.
.SH "OPTIONS"
.PP
<commit>
.RS 4
Commit to revert\. For a more complete list of ways to spell commit names, see "SPECIFYING REVISIONS" section in \fBgit-rev-parse\fR(1)\.
.RE
.PP
\-e, \-\-edit
.RS 4
With this option, \fIgit\-revert\fR will let you edit the commit message prior to committing the revert\. This is the default if you run the command from a terminal\.
.RE
.PP
\-m parent\-number, \-\-mainline parent\-number
.RS 4
Usually you cannot revert a merge because you do not know which side of the merge should be considered the mainline\. This option specifies the parent number (starting from 1) of the mainline and allows revert to reverse the change relative to the specified parent\.
.RE
.PP
\-\-no\-edit
.RS 4
With this option, \fIgit\-revert\fR will not start the commit message editor\.
.RE
.PP
\-n, \-\-no\-commit
.RS 4
Usually the command automatically creates a commit with a commit log message stating which commit was reverted\. This flag applies the change necessary to revert the named commit to your working tree and the index, but does not make the commit\. In addition, when this option is used, your index does not have to match the HEAD commit\. The revert is done against the beginning state of your index\.

This is useful when reverting more than one commits\' effect to your index in a row\.
.RE
.PP
\-s, \-\-signoff
.RS 4
Add Signed\-off\-by line at the end of the commit message\.
.RE
.SH "AUTHOR"
Written by Junio C Hamano <gitster@pobox\.com>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano and the git\-list <git@vger\.kernel\.org>\.
.SH "GIT"
Part of the \fBgit\fR(1) suite

