.\"     Title: git-check-attr
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 03/26/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.2.1.389.geed1
.\"
.TH "GIT\-CHECK\-ATTR" "1" "03/26/2009" "Git 1\.6\.2\.1\.389\.geed1" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-check-attr - Display gitattributes information
.SH "SYNOPSIS"
.sp
.RS 4
.nf
\fIgit check\-attr\fR attr\&... [\-\-] pathname\&...
\fIgit check\-attr\fR \-\-stdin [\-z] attr\&... < <list\-of\-paths>
.fi
.RE
.SH "DESCRIPTION"
For every pathname, this command will list if each attribute is \fIunspecified\fR, \fIset\fR, or \fIunset\fR as a gitattribute on that pathname\.
.SH "OPTIONS"
.PP
\-\-stdin
.RS 4
Read file names from stdin instead of from the command\-line\.
.RE
.PP
\-z
.RS 4
Only meaningful with \-\-stdin; paths are separated with a NUL character instead of a linefeed character\.
.RE
.PP
\-\-
.RS 4
Interpret all preceding arguments as attributes and all following arguments as path names\. If not supplied, only the first argument will be treated as an attribute\.
.RE
.SH "OUTPUT"
The output is of the form: <path> COLON SP <attribute> COLON SP <info> LF

<path> is the path of a file being queried, <attribute> is an attribute being queried and <info> can be either:
.TS
tab(:);
lt lt
lt lt
lt lt
lt lt.
T{
\fIunspecified\fR
T}:T{
when the attribute is not defined for the path\.
T}
T{
\fIunset\fR
T}:T{
when the attribute is defined as false\.
T}
T{
\fIset\fR
T}:T{
when the attribute is defined as true\.
T}
T{
<value>
T}:T{
when a value has been assigned to the attribute\.
T}
.TE
.sp
.SH "EXAMPLES"
In the examples, the following \fI\.gitattributes\fR file is used:

.sp
.RS 4
.nf

\.ft C
*\.java diff=java \-crlf myAttr
NoMyAttr\.java !myAttr
README caveat=unspecified
\.ft

.fi
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Listing a single attribute:
.RE
.sp
.RS 4
.nf

\.ft C
$ git check\-attr diff org/example/MyClass\.java
org/example/MyClass\.java: diff: java
\.ft

.fi
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Listing multiple attributes for a file:
.RE
.sp
.RS 4
.nf

\.ft C
$ git check\-attr crlf diff myAttr \-\- org/example/MyClass\.java
org/example/MyClass\.java: crlf: unset
org/example/MyClass\.java: diff: java
org/example/MyClass\.java: myAttr: set
\.ft

.fi
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Listing an attribute for multiple files:
.RE
.sp
.RS 4
.nf

\.ft C
$ git check\-attr myAttr \-\- org/example/MyClass\.java org/example/NoMyAttr\.java
org/example/MyClass\.java: myAttr: set
org/example/NoMyAttr\.java: myAttr: unspecified
\.ft

.fi
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'Not all values are equally unambiguous:
.RE
.sp
.RS 4
.nf

\.ft C
$ git check\-attr caveat README
README: caveat: unspecified
\.ft

.fi
.RE
.SH "SEE ALSO"
\fBgitattributes\fR(5)\.
.SH "AUTHOR"
Written by Junio C Hamano <gitster@pobox\.com>
.SH "DOCUMENTATION"
Documentation by James Bowes\.
.SH "GIT"
Part of the \fBgit\fR(1) suite

