.\"     Title: git-branch
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 03/22/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.2.1.299.g88f78
.\"
.TH "GIT\-BRANCH" "1" "03/22/2009" "Git 1\.6\.2\.1\.299\.g88f78" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-branch - List, create, or delete branches
.SH "SYNOPSIS"
.sp
.RS 4
.nf
\fIgit branch\fR [\-\-color | \-\-no\-color] [\-r | \-a]
        [\-v [\-\-abbrev=<length> | \-\-no\-abbrev]]
        [(\-\-merged | \-\-no\-merged | \-\-contains) [<commit>]]
\fIgit branch\fR [\-\-track | \-\-no\-track] [\-l] [\-f] <branchname> [<start\-point>]
\fIgit branch\fR (\-m | \-M) [<oldbranch>] <newbranch>
\fIgit branch\fR (\-d | \-D) [\-r] <branchname>\&...
.fi
.RE
.SH "DESCRIPTION"
With no arguments, existing branches are listed and the current branch will be highlighted with an asterisk\. Option \-r causes the remote\-tracking branches to be listed, and option \-a shows both\.

With \-\-contains, shows only the branches that contain the named commit (in other words, the branches whose tip commits are descendants of the named commit)\. With \-\-merged, only branches merged into the named commit (i\.e\. the branches whose tip commits are reachable from the named commit) will be listed\. With \-\-no\-merged only branches not merged into the named commit will be listed\. If the <commit> argument is missing it defaults to \fIHEAD\fR (i\.e\. the tip of the current branch)\.

In the command\'s second form, a new branch named <branchname> will be created\. It will start out with a head equal to the one given as <start\-point>\. If no <start\-point> is given, the branch will be created with a head equal to that of the currently checked out branch\.

Note that this will create the new branch, but it will not switch the working tree to it; use "git checkout <newbranch>" to switch to the new branch\.

When a local branch is started off a remote branch, git sets up the branch so that \fIgit\-pull\fR will appropriately merge from the remote branch\. This behavior may be changed via the global branch\.autosetupmerge configuration flag\. That setting can be overridden by using the \-\-track and \-\-no\-track options\.

With a \fI\-m\fR or \fI\-M\fR option, <oldbranch> will be renamed to <newbranch>\. If <oldbranch> had a corresponding reflog, it is renamed to match <newbranch>, and a reflog entry is created to remember the branch renaming\. If <newbranch> exists, \-M must be used to force the rename to happen\.

With a \-d or \-D option, <branchname> will be deleted\. You may specify more than one branch for deletion\. If the branch currently has a reflog then the reflog will also be deleted\.

Use \-r together with \-d to delete remote\-tracking branches\. Note, that it only makes sense to delete remote\-tracking branches if they no longer exist in the remote repository or if \fIgit\-fetch\fR was configured not to fetch them again\. See also the \fIprune\fR subcommand of \fBgit-remote\fR(1) for a way to clean up all obsolete remote\-tracking branches\.
.SH "OPTIONS"
.PP
\-d
.RS 4
Delete a branch\. The branch must be fully merged in HEAD\.
.RE
.PP
\-D
.RS 4
Delete a branch irrespective of its merged status\.
.RE
.PP
\-l
.RS 4
Create the branch\'s reflog\. This activates recording of all changes made to the branch ref, enabling use of date based sha1 expressions such as "<branchname>@{yesterday}"\.
.RE
.PP
\-f
.RS 4
Reset <branchname> to <startpoint> if <branchname> exists already\. Without \-f \fIgit\-branch\fR refuses to change an existing branch\.
.RE
.PP
\-m
.RS 4
Move/rename a branch and the corresponding reflog\.
.RE
.PP
\-M
.RS 4
Move/rename a branch even if the new branch name already exists\.
.RE
.PP
\-\-color
.RS 4
Color branches to highlight current, local, and remote branches\.
.RE
.PP
\-\-no\-color
.RS 4
Turn off branch colors, even when the configuration file gives the default to color output\.
.RE
.PP
\-r
.RS 4
List or delete (if used with \-d) the remote\-tracking branches\.
.RE
.PP
\-a
.RS 4
List both remote\-tracking branches and local branches\.
.RE
.PP
\-v, \-\-verbose
.RS 4
Show sha1 and commit subject line for each head\.
.RE
.PP
\-\-abbrev=<length>
.RS 4
Alter the sha1\'s minimum display length in the output listing\. The default value is 7\.
.RE
.PP
\-\-no\-abbrev
.RS 4
Display the full sha1s in the output listing rather than abbreviating them\.
.RE
.PP
\-\-track
.RS 4
When creating a new branch, set up the configuration so that \fIgit\-pull\fR will automatically retrieve data from the start point, which must be a branch\. Use this if you always pull from the same upstream branch into the new branch, and if you do not want to use "git pull <repository> <refspec>" explicitly\. This behavior is the default when the start point is a remote branch\. Set the branch\.autosetupmerge configuration variable to false if you want \fIgit\-checkout\fR and \fIgit\-branch\fR to always behave as if \fI\-\-no\-track\fR were given\. Set it to always if you want this behavior when the start\-point is either a local or remote branch\.
.RE
.PP
\-\-no\-track
.RS 4
Ignore the branch\.autosetupmerge configuration variable\.
.RE
.PP
\-\-contains <commit>
.RS 4
Only list branches which contain the specified commit\.
.RE
.PP
\-\-merged
.RS 4
Only list branches which are fully contained by HEAD\.
.RE
.PP
\-\-no\-merged
.RS 4
Do not list branches which are fully contained by HEAD\.
.RE
.PP
<branchname>
.RS 4
The name of the branch to create or delete\. The new branch name must pass all checks defined by \fBgit-check-ref-format\fR(1)\. Some of these checks may restrict the characters allowed in a branch name\.
.RE
.PP
<start\-point>
.RS 4
The new branch will be created with a HEAD equal to this\. It may be given as a branch name, a commit\-id, or a tag\. If this option is omitted, the current branch is assumed\.
.RE
.PP
<oldbranch>
.RS 4
The name of an existing branch to rename\.
.RE
.PP
<newbranch>
.RS 4
The new name for an existing branch\. The same restrictions as for <branchname> apply\.
.RE
.SH "EXAMPLES"
.PP
Start development from a known tag
.RS 4
.sp
.RS 4
.nf

\.ft C
$ git clone git://git\.kernel\.org/pub/scm/\.\.\./linux\-2\.6 my2\.6
$ cd my2\.6
$ git branch my2\.6\.14 v2\.6\.14   \fB(1)\fR
$ git checkout my2\.6\.14
\.ft

.fi
.RE
.sp
\fB1. \fRThis step and the next one could be combined into a single step with "checkout \-b my2\.6\.14 v2\.6\.14"\.
.br
.RE
.PP
Delete an unneeded branch
.RS 4
.sp
.RS 4
.nf

\.ft C
$ git clone git://git\.kernel\.org/\.\.\./git\.git my\.git
$ cd my\.git
$ git branch \-d \-r origin/todo origin/html origin/man   \fB(1)\fR
$ git branch \-D test                                    \fB(2)\fR
\.ft

.fi
.RE
.sp
\fB1. \fRDelete the remote\-tracking branches "todo", "html" and "man"\. The next \fIfetch\fR or \fIpull\fR will create them again unless you configure them not to\. See \fBgit-fetch\fR(1)\.
.br
\fB2. \fRDelete the "test" branch even if the "master" branch (or whichever branch is currently checked out) does not have all commits from the test branch\.
.br
.RE
.SH "NOTES"
If you are creating a branch that you want to checkout immediately, it is easier to use the git checkout command with its \-b option to create a branch and check it out with a single command\.

The options \-\-contains, \-\-merged and \-\-no\-merged serve three related but different purposes:

.sp
.RS 4
\h'-04'\(bu\h'+03'\-\-contains <commit> is used to find all branches which will need special attention if <commit> were to be rebased or amended, since those branches contain the specified <commit>\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'\-\-merged is used to find all branches which can be safely deleted, since those branches are fully contained by HEAD\.
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'\-\-no\-merged is used to find branches which are candidates for merging into HEAD, since those branches are not fully contained by HEAD\.
.RE
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl\.org> and Junio C Hamano <gitster@pobox\.com>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano and the git\-list <git@vger\.kernel\.org>\.
.SH "GIT"
Part of the \fBgit\fR(1) suite

