.\"     Title: git-shell
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 04/02/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.2.rc0.64.ge9cc0
.\"
.TH "GIT\-SHELL" "1" "04/02/2009" "Git 1\.6\.2\.rc0\.64\.ge9cc0" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-shell - Restricted login shell for GIT-only SSH access
.SH "SYNOPSIS"
\fI$(git \-\-exec\-path)/git\-shell\fR \-c <command> <argument>
.sp
.SH "DESCRIPTION"
This is meant to be used as a login shell for SSH accounts you want to restrict to GIT pull/push access only\. It permits execution only of server\-side GIT commands implementing the pull/push functionality\. The commands can be executed only by the \fI\-c\fR option; the shell is not interactive\.
.sp
Currently, only three commands are permitted to be called, \fIgit\-receive\-pack\fR \fIgit\-upload\-pack\fR with a single required argument or \fIcvs server\fR (to invoke \fIgit\-cvsserver\fR)\.
.sp
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl\.org>
.sp
.SH "DOCUMENTATION"
Documentation by Petr Baudis and the git\-list <git@vger\.kernel\.org>\.
.sp
.SH "GIT"
Part of the \fBgit\fR(1) suite
.sp
