.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-HELP" "1" "12/04/2007" "Git 1.5.3.7.1005.gdada0c" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-help \- display help information about git
.SH "SYNOPSIS"
\fIgit help\fR [\-a|\-\-all] [COMMAND]
.SH "DESCRIPTION"
With no options and no COMMAND given, the synopsis of the \fIgit\fR command and a list of the most commonly used git commands are printed on the standard output.

If the option \fI\-\-all\fR or \fI\-a\fR is given, then all available commands are printed on the standard output.

If a git command is named, a manual page for that command is brought up. The \fIman\fR program is used by default for this purpose.

Note that \fIgit \-\-help \&...\fR is identical as \fIgit help \&...\fR because the former is internally converted into the latter.
.SH "OPTIONS"
.TP
\-a|\-\-all
Prints all the available commands on the standard output. This option superseeds any other option.
.SH "AUTHOR"
Written by Junio C Hamano <gitster@pobox.com> and the git\-list <git@vger.kernel.org>.
.SH "DOCUMENTATION"
Initial documentation was part of the \fBgit\fR(7) man page. Christian Couder <chriscool@tuxfamily.org> extracted and rewrote it a little. Maintenance is done by the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

