.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-MERGE\-BASE" "1" "06/08/2008" "Git 1.5.6.rc2" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-merge\-base \- Find as good common ancestors as possible for a merge
.SH "SYNOPSIS"
\fIgit\-merge\-base\fR [\-\-all] <commit> <commit>
.SH "DESCRIPTION"
"git\-merge\-base" finds as good a common ancestor as possible between the two commits. That is, given two commits A and B \fIgit\-merge\-base A B\fR will output a commit which is reachable from both A and B through the parent relationship.

Given a selection of equally good common ancestors it should not be relied on to decide in any particular way.

The "git\-merge\-base" algorithm is still in flux \- use the source\&...
.SH "OPTIONS"
.TP
\-\-all
Output all common ancestors for the two commits instead of just one.
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl.org>
.SH "DOCUMENTATION"
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(1) suite

