.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-GET\-TAR\-COMMIT\-I" "1" "06/08/2008" "Git 1.5.6.rc2" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-get\-tar\-commit\-id \- Extract commit ID from an archive created using git\-archive
.SH "SYNOPSIS"
\fIgit\-get\-tar\-commit\-id\fR < <tarfile>
.SH "DESCRIPTION"
Acts as a filter, extracting the commit ID stored in archives created by \fBgit\-archive\fR(1). It reads only the first 1024 bytes of input, thus its runtime is not influenced by the size of <tarfile> very much.

If no commit ID is found, git\-get\-tar\-commit\-id quietly exists with a return code of 1. This can happen if <tarfile> had not been created using git\-archive or if the first parameter of git\-archive had been a tree ID instead of a commit ID or tag.
.SH "AUTHOR"
Written by Rene Scharfe <rene.scharfe@lsrfire.ath.cx>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano and the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(1) suite

