.\"     Title: git-mailinfo
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 04/02/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.2.rc0.64.ge9cc0
.\"
.TH "GIT\-MAILINFO" "1" "04/02/2009" "Git 1\.6\.2\.rc0\.64\.ge9cc0" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-mailinfo - Extracts patch and authorship from a single e-mail message
.SH "SYNOPSIS"
\fIgit mailinfo\fR [\-k] [\-u | \-\-encoding=<encoding> | \-n] <msg> <patch>
.sp
.SH "DESCRIPTION"
Reads a single e\-mail message from the standard input, and writes the commit log message in <msg> file, and the patches in <patch> file\. The author name, e\-mail and e\-mail subject are written out to the standard output to be used by \fIgit\-am\fR to create a commit\. It is usually not necessary to use this command directly\. See \fBgit-am\fR(1) instead\.
.sp
.SH "OPTIONS"
.PP
\-k
.RS 4
Usually the program
\fIcleans up\fR
the Subject: header line to extract the title line for the commit log message, among which (1) remove
\fIRe:\fR
or
\fIre:\fR, (2) leading whitespaces, (3)
\fI[\fR
up to
\fI]\fR, typically
\fI[PATCH]\fR, and then prepends "[PATCH] "\. This flag forbids this munging, and is most useful when used to read back
\fIgit\-format\-patch \-k\fR
output\.
.RE
.PP
\-u
.RS 4
The commit log message, author name and author email are taken from the e\-mail, and after minimally decoding MIME transfer encoding, re\-coded in UTF\-8 by transliterating them\. This used to be optional but now it is the default\.
.sp
Note that the patch is always used as\-is without charset conversion, even with this flag\.
.RE
.PP
\-\-encoding=<encoding>
.RS 4
Similar to \-u but if the local convention is different from what is specified by i18n\.commitencoding, this flag can be used to override it\.
.RE
.PP
\-n
.RS 4
Disable all charset re\-coding of the metadata\.
.RE
.PP
<msg>
.RS 4
The commit log message extracted from e\-mail, usually except the title line which comes from e\-mail Subject\.
.RE
.PP
<patch>
.RS 4
The patch extracted from e\-mail\.
.RE
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl\.org> and Junio C Hamano <gitster@pobox\.com>
.sp
.SH "DOCUMENTATION"
Documentation by Junio C Hamano and the git\-list <git@vger\.kernel\.org>\.
.sp
.SH "GIT"
Part of the \fBgit\fR(1) suite
.sp
