.\"     Title: git-update-server-info
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 09/19/2008
.\"    Manual: Git Manual
.\"    Source: Git 1.6.0.2.287.g3791f
.\"
.TH "GIT\-UPDATE\-SERVER\" "1" "09/19/2008" "Git 1\.6\.0\.2\.287\.g3791f" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-update-server-info - Update auxiliary info file to help dumb servers
.SH "SYNOPSIS"
\fIgit update\-server\-info\fR [\-\-force]
.SH "DESCRIPTION"
A dumb server that does not do on\-the\-fly pack generations must have some auxiliary information files in $GIT_DIR/info and $GIT_OBJECT_DIRECTORY/info directories to help clients discover what references and packs the server has\. This command generates such auxiliary files\.
.SH "OPTIONS"
.PP
\-f, \-\-force
.RS 4
Update the info files from scratch\.
.RE
.SH "OUTPUT"
Currently the command updates the following files\. Please see \fBgitrepository-layout\fR(5) for description of what they are for:

.sp
.RS 4
\h'-04'\(bu\h'+03'objects/info/packs
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'info/refs
.RE
.SH "BUGS"
When you remove an existing ref, the command fails to update info/refs file unless \-\-force flag is given\.
.SH "AUTHOR"
Written by Junio C Hamano <gitster@pobox\.com>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano\.
.SH "GIT"
Part of the \fBgit\fR(1) suite

