'\" t
.\"     Title: git-clean
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 12/03/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.6.rc1.5.ge21a85
.\"  Language: English
.\"
.TH "GIT\-CLEAN" "1" "12/03/2009" "Git 1\&.6\&.6\&.rc1\&.5\&.ge21" "Git Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-clean \- Remove untracked files from the working tree
.SH "SYNOPSIS"
.sp
.nf
\fIgit clean\fR [\-d] [\-f] [\-n] [\-q] [\-x | \-X] [\-\-] <path>\&...
.fi
.sp
.SH "DESCRIPTION"
.sp
Cleans the working tree by recursively removing files that are not under version control, starting from the current directory\&.
.sp
Normally, only files unknown to git are removed, but if the \fI\-x\fR option is specified, ignored files are also removed\&. This can, for example, be useful to remove all build products\&.
.sp
If any optional <path>\&... arguments are given, only those paths are affected\&.
.SH "OPTIONS"
.PP
\-d
.RS 4
Remove untracked directories in addition to untracked files\&. If an untracked directory is managed by a different git repository, it is not removed by default\&. Use \-f option twice if you really want to remove such a directory\&.
.RE
.PP
\-f, \-\-force
.RS 4
If the git configuration specifies clean\&.requireForce as true,
\fIgit\-clean\fR
will refuse to run unless given \-f or \-n\&.
.RE
.PP
\-n, \-\-dry\-run
.RS 4
Don\(aqt actually remove anything, just show what would be done\&.
.RE
.PP
\-q, \-\-quiet
.RS 4
Be quiet, only report errors, but not the files that are successfully removed\&.
.RE
.PP
\-x
.RS 4
Don\(aqt use the ignore rules\&. This allows removing all untracked files, including build products\&. This can be used (possibly in conjunction with
\fIgit\-reset\fR) to create a pristine working directory to test a clean build\&.
.RE
.PP
\-X
.RS 4
Remove only files ignored by git\&. This may be useful to rebuild everything from scratch, but keep manually created files\&.
.RE
.SH "AUTHOR"
.sp
Written by Pavel Roskin <proski@gnu\&.org>
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
