.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-PRUNE" "1" "01/21/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-prune \- Prunes all unreachable objects from the object database
.SH "SYNOPSIS"
\fIgit\-prune\fR [\-n] [\-\-grace=<time>]
.SH "DESCRIPTION"
This runs git\-fsck\-objects \-\-unreachable using all the refs available in $GIT_DIR/refs, optionally with additional set of objects specified on the command line, and prunes all objects unreachable from any of these head objects from the object database. In addition, it prunes the unpacked objects that are also found in packs by running git prune\-packed.
.SH "OPTIONS"
.TP
\-n
Do not remove anything; just report what it would remove.
.TP
\-\-grace=<time>
Do not prune loose objects that are younger than the specified time. This gives a grace period to newly created objects from getting pruned.
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl.org>
.SH "DOCUMENTATION"
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

