.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-RELINK" "1" "04/04/2007" "Git 1.5.1.31.ge421f" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-relink \- Hardlink common objects in local repositories
.SH "SYNOPSIS"
\fIgit\-relink\fR [\-\-safe] <dir> <dir> [<dir>]*
.SH "DESCRIPTION"
This will scan 2 or more object repositories and look for common objects, check if they are hardlinked, and replace one with a hardlink to the other if not.
.SH "OPTIONS"
.TP
\-\-safe
Stops if two objects with the same hash exist but have different sizes. Default is to warn and continue.
.TP
<dir>
Directories containing a .git/objects/ subdirectory.
.SH "AUTHOR"
Written by Ryan Anderson <ryan@michonline.com>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano and the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

