.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-MERGETOOL" "1" "05/04/2007" "Git 1.5.2.rc1.20.g86b9" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-mergetool \- Run merge conflict resolution tools to resolve merge conflicts
.SH "SYNOPSIS"
\fIgit\-mergetool\fR [\-\-tool=<tool>] [<file>]\&...
.SH "DESCRIPTION"
Use \fIgit mergetool\fR to run one of several merge utilities to resolve merge conflicts. It is typically run after \fBgit\-merge\fR(1).

If one or more <file> parameters are given, the merge tool program will be run to resolve differences on each file. If no <file> names are specified, \fIgit mergetool\fR will run the merge tool program on every file with merge conflicts.
.SH "OPTIONS"
.TP
\-t or \-\-tool=<tool>
Use the merge resolution program specified by <tool>. Valid merge tools are: kdiff3, tkdiff, meld, xxdiff, emerge, vimdiff, and opendiff

If a merge resolution program is not specified, \fIgit mergetool\fR will use the configuration variable merge.tool. If the configuration variable merge.tool is not set, \fIgit mergetool\fR will pick a suitable default.
.SH "AUTHOR"
Written by Theodore Y Ts'o <tytso@mit.edu>
.SH "DOCUMENTATION"
Documentation by Theodore Y Ts'o.
.SH "GIT"
Part of the \fBgit\fR(7) suite

