.\"     Title: git-verify-tag
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 09/19/2008
.\"    Manual: Git Manual
.\"    Source: Git 1.6.0.2.287.g3791f
.\"
.TH "GIT\-VERIFY\-TAG" "1" "09/19/2008" "Git 1\.6\.0\.2\.287\.g3791f" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-verify-tag - Check the GPG signature of tags
.SH "SYNOPSIS"
\fIgit verify\-tag\fR <tag>\&...
.SH "DESCRIPTION"
Validates the gpg signature created by \fIgit\-tag\fR\.
.SH "OPTIONS"
.PP
<tag>\&...
.RS 4
SHA1 identifiers of git tag objects\.
.RE
.SH "AUTHOR"
Written by Jan Harkes <jaharkes@cs\.cmu\.edu> and Eric W\. Biederman <ebiederm@xmission\.com>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano and the git\-list <git@vger\.kernel\.org>\.
.SH "GIT"
Part of the \fBgit\fR(1) suite

