.\"     Title: git-merge-one-file
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 04/02/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.2.rc0.64.ge9cc0
.\"
.TH "GIT\-MERGE\-ONE\-FIL" "1" "04/02/2009" "Git 1\.6\.2\.rc0\.64\.ge9cc0" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-merge-one-file - The standard helper program to use with git-merge-index
.SH "SYNOPSIS"
\fIgit\-merge\-one\-file\fR
.sp
.SH "DESCRIPTION"
This is the standard helper program to use with \fIgit\-merge\-index\fR to resolve a merge after the trivial merge done with \fIgit\-read\-tree \-m\fR\.
.sp
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl\.org>, Junio C Hamano <gitster@pobox\.com> and Petr Baudis <pasky@suse\.cz>\.
.sp
.SH "DOCUMENTATION"
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger\.kernel\.org>\.
.sp
.SH "GIT"
Part of the \fBgit\fR(1) suite
.sp
