.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-INDEX\-PACK" "1" "10/03/2006" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-index\-pack \- Build pack index file for an existing packed archive
.SH "SYNOPSIS"
\fIgit\-index\-pack\fR [\-o <index\-file>] <pack\-file>
.sp
.SH "DESCRIPTION"
Reads a packed archive (.pack) from the specified file, and builds a pack index file (.idx) for it. The packed archive together with the pack index can then be placed in the objects/pack/ directory of a git repository.
.sp
.SH "OPTIONS"
.TP
\-o <index\-file>
Write the generated pack index into the specified file. Without this option the name of pack index file is constructed from the name of packed archive file by replacing .pack with .idx (and the program fails if the name of packed archive does not end with .pack).
.SH "AUTHOR"
Written by Sergey Vlasov <vsu@altlinux.ru>
.sp
.SH "DOCUMENTATION"
Documentation by Sergey Vlasov
.sp
.SH "GIT"
Part of the \fBgit\fR(7) suite
.sp
