.\"     Title: git-clean
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 07/06/2008
.\"    Manual: Git Manual
.\"    Source: Git 1.5.6.2.212.g08b5
.\"
.TH "GIT\-CLEAN" "1" "07/06/2008" "Git 1\.5\.6\.2\.212\.g08b5" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-clean - Remove untracked files from the working tree
.SH "SYNOPSIS"
.sp
.RS 4
.nf
\fIgit clean\fR [\-d] [\-f] [\-n] [\-q] [\-x | \-X] [\-\-] <paths>\&...
.fi
.RE
.SH "DESCRIPTION"
Removes files unknown to git\. This allows to clean the working tree from files that are not under version control\. If the \fI\-x\fR option is specified, ignored files are also removed, allowing to remove all build products\. When optional <paths>\&... arguments are given, the paths affected are further limited to those that match them\.
.SH "OPTIONS"
.PP
\-d
.RS 4
Remove untracked directories in addition to untracked files\.
.RE
.PP
\-f
.RS 4
If the git configuration specifies clean\.requireForce as true, \fIgit\-clean\fR will refuse to run unless given \-f or \-n\.
.RE
.PP
\-n, \-\-dry\-run
.RS 4
Don\'t actually remove anything, just show what would be done\.
.RE
.PP
\-q, \-\-quiet
.RS 4
Be quiet, only report errors, but not the files that are successfully removed\.
.RE
.PP
\-x
.RS 4
Don\'t use the ignore rules\. This allows removing all untracked files, including build products\. This can be used (possibly in conjunction with \fIgit\-reset\fR) to create a pristine working directory to test a clean build\.
.RE
.PP
\-X
.RS 4
Remove only files ignored by git\. This may be useful to rebuild everything from scratch, but keep manually created files\.
.RE
.SH "AUTHOR"
Written by Pavel Roskin <proski@gnu\.org>
.SH "GIT"
Part of the \fBgit\fR(1) suite

