'\" t
.\"     Title: git-cat-file
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.78.1 <http://docbook.sf.net/>
.\"      Date: 11/26/2014
.\"    Manual: Git Manual
.\"    Source: Git
.\"  Language: English
.\"
.TH "GIT\-CAT\-FILE" "1" "11/26/2014" "Git" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-cat-file \- Provide content or type and size information for repository objects
.SH "SYNOPSIS"
.sp
.nf
\fIgit cat\-file\fR (\-t | \-s | \-e | \-p | <type> | \-\-textconv ) <object>
\fIgit cat\-file\fR (\-\-batch | \-\-batch\-check) < <list\-of\-objects>
.fi
.sp
.SH "DESCRIPTION"
.sp
In its first form, the command provides the content or the type of an object in the repository\&. The type is required unless \fI\-t\fR or \fI\-p\fR is used to find the object type, or \fI\-s\fR is used to find the object size, or \fI\-\-textconv\fR is used (which implies type "blob")\&.
.sp
In the second form, a list of objects (separated by linefeeds) is provided on stdin, and the SHA\-1, type, and size of each object is printed on stdout\&.
.SH "OPTIONS"
.PP
<object>
.RS 4
The name of the object to show\&. For a more complete list of ways to spell object names, see the "SPECIFYING REVISIONS" section in
\fBgitrevisions\fR(7)\&.
.RE
.PP
\-t
.RS 4
Instead of the content, show the object type identified by <object>\&.
.RE
.PP
\-s
.RS 4
Instead of the content, show the object size identified by <object>\&.
.RE
.PP
\-e
.RS 4
Suppress all output; instead exit with zero status if <object> exists and is a valid object\&.
.RE
.PP
\-p
.RS 4
Pretty\-print the contents of <object> based on its type\&.
.RE
.PP
<type>
.RS 4
Typically this matches the real type of <object> but asking for a type that can trivially be dereferenced from the given <object> is also permitted\&. An example is to ask for a "tree" with <object> being a commit object that contains it, or to ask for a "blob" with <object> being a tag object that points at it\&.
.RE
.PP
\-\-textconv
.RS 4
Show the content as transformed by a textconv filter\&. In this case, <object> has be of the form <tree\-ish>:<path>, or :<path> in order to apply the filter to the content recorded in the index at <path>\&.
.RE
.PP
\-\-batch, \-\-batch=<format>
.RS 4
Print object information and contents for each object provided on stdin\&. May not be combined with any other options or arguments\&. See the section
BATCH OUTPUT
below for details\&.
.RE
.PP
\-\-batch\-check, \-\-batch\-check=<format>
.RS 4
Print object information for each object provided on stdin\&. May not be combined with any other options or arguments\&. See the section
BATCH OUTPUT
below for details\&.
.RE
.SH "OUTPUT"
.sp
If \fI\-t\fR is specified, one of the <type>\&.
.sp
If \fI\-s\fR is specified, the size of the <object> in bytes\&.
.sp
If \fI\-e\fR is specified, no output\&.
.sp
If \fI\-p\fR is specified, the contents of <object> are pretty\-printed\&.
.sp
If <type> is specified, the raw (though uncompressed) contents of the <object> will be returned\&.
.SH "BATCH OUTPUT"
.sp
If \-\-batch or \-\-batch\-check is given, cat\-file will read objects from stdin, one per line, and print information about them\&. By default, the whole line is considered as an object, as if it were fed to \fBgit-rev-parse\fR(1)\&.
.sp
You can specify the information shown for each object by using a custom <format>\&. The <format> is copied literally to stdout for each object, with placeholders of the form %(atom) expanded, followed by a newline\&. The available atoms are:
.PP
objectname
.RS 4
The 40\-hex object name of the object\&.
.RE
.PP
objecttype
.RS 4
The type of of the object (the same as
cat\-file \-t
reports)\&.
.RE
.PP
objectsize
.RS 4
The size, in bytes, of the object (the same as
cat\-file \-s
reports)\&.
.RE
.PP
objectsize:disk
.RS 4
The size, in bytes, that the object takes up on disk\&. See the note about on\-disk sizes in the
CAVEATS
section below\&.
.RE
.PP
deltabase
.RS 4
If the object is stored as a delta on\-disk, this expands to the 40\-hex sha1 of the delta base object\&. Otherwise, expands to the null sha1 (40 zeroes)\&. See
CAVEATS
below\&.
.RE
.PP
rest
.RS 4
If this atom is used in the output string, input lines are split at the first whitespace boundary\&. All characters before that whitespace are considered to be the object name; characters after that first run of whitespace (i\&.e\&., the "rest" of the line) are output in place of the
%(rest)
atom\&.
.RE
.sp
If no format is specified, the default format is %(objectname) %(objecttype) %(objectsize)\&.
.sp
If \-\-batch is specified, the object information is followed by the object contents (consisting of %(objectsize) bytes), followed by a newline\&.
.sp
For example, \-\-batch without a custom format would produce:
.sp
.if n \{\
.RS 4
.\}
.nf
<sha1> SP <type> SP <size> LF
<contents> LF
.fi
.if n \{\
.RE
.\}
.sp
.sp
Whereas \-\-batch\-check=\(aq%(objectname) %(objecttype)\(aq would produce:
.sp
.if n \{\
.RS 4
.\}
.nf
<sha1> SP <type> LF
.fi
.if n \{\
.RE
.\}
.sp
.sp
If a name is specified on stdin that cannot be resolved to an object in the repository, then cat\-file will ignore any custom format and print:
.sp
.if n \{\
.RS 4
.\}
.nf
<object> SP missing LF
.fi
.if n \{\
.RE
.\}
.sp
.SH "CAVEATS"
.sp
Note that the sizes of objects on disk are reported accurately, but care should be taken in drawing conclusions about which refs or objects are responsible for disk usage\&. The size of a packed non\-delta object may be much larger than the size of objects which delta against it, but the choice of which object is the base and which is the delta is arbitrary and is subject to change during a repack\&.
.sp
Note also that multiple copies of an object may be present in the object database; in this case, it is undefined which copy\(cqs size or delta base will be reported\&.
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
