.\"     Title: git-fmt-merge-msg
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 04/02/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.2.rc0.64.ge9cc0
.\"
.TH "GIT\-FMT\-MERGE\-MSG" "1" "04/02/2009" "Git 1\.6\.2\.rc0\.64\.ge9cc0" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-fmt-merge-msg - Produce a merge commit message
.SH "SYNOPSIS"
.sp
.RS 4
.nf
\fIgit fmt\-merge\-msg\fR [\-\-log | \-\-no\-log] <$GIT_DIR/FETCH_HEAD
\fIgit fmt\-merge\-msg\fR [\-\-log | \-\-no\-log] \-F <file>
.fi
.RE
.SH "DESCRIPTION"
Takes the list of merged objects on stdin and produces a suitable commit message to be used for the merge commit, usually to be passed as the \fI<merge\-message>\fR argument of \fIgit\-merge\fR\.
.sp
This script is intended mostly for internal use by scripts automatically invoking \fIgit\-merge\fR\.
.sp
.SH "OPTIONS"
.PP
\-\-log
.RS 4
In addition to branch names, populate the log message with one\-line descriptions from the actual commits that are being merged\.
.RE
.PP
\-\-no\-log
.RS 4
Do not list one\-line descriptions from the actual commits being merged\.
.RE
.PP
\-\-summary, \-\-no\-summary
.RS 4
Synonyms to \-\-log and \-\-no\-log; these are deprecated and will be removed in the future\.
.RE
.PP
\-F <file>, \-\-file <file>
.RS 4
Take the list of merged objects from <file> instead of stdin\.
.RE
.SH "CONFIGURATION"
.PP
merge\.log
.RS 4
Whether to include summaries of merged commits in newly merge commit messages\. False by default\.
.RE
.PP
merge\.summary
.RS 4
Synonym to
merge\.log; this is deprecated and will be removed in the future\.
.RE
.SH "SEE ALSO"
\fBgit-merge\fR(1)
.sp
.SH "AUTHOR"
Written by Junio C Hamano <gitster@pobox\.com>
.sp
.SH "DOCUMENTATION"
Documentation by Petr Baudis, Junio C Hamano and the git\-list <git@vger\.kernel\.org>\.
.sp
.SH "GIT"
Part of the \fBgit\fR(1) suite
.sp
