.\"     Title: git-upload-pack
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 12/10/2008
.\"    Manual: Git Manual
.\"    Source: Git 1.6.0.2.287.g3791f
.\"
.TH "GIT\-UPLOAD\-PACK" "1" "12/10/2008" "Git 1\.6\.0\.2\.287\.g3791f" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-upload-pack - Send objects packed back to git-fetch-pack
.SH "SYNOPSIS"
\fIgit upload\-pack\fR [\-\-strict] [\-\-timeout=<n>] <directory>
.SH "DESCRIPTION"
Invoked by \fIgit\-fetch\-pack\fR, learns what objects the other side is missing, and sends them after packing\.

This command is usually not invoked directly by the end user\. The UI for the protocol is on the \fIgit\-fetch\-pack\fR side, and the program pair is meant to be used to pull updates from a remote repository\. For push operations, see \fIgit\-send\-pack\fR\.
.SH "OPTIONS"
.PP
\-\-strict
.RS 4
Do not try <directory>/\.git/ if <directory> is no git directory\.
.RE
.PP
\-\-timeout=<n>
.RS 4
Interrupt transfer after <n> seconds of inactivity\.
.RE
.PP
<directory>
.RS 4
The repository to sync from\.
.RE
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl\.org>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano\.
.SH "GIT"
Part of the \fBgit\fR(1) suite

