.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-REMOTE" "1" "01/29/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-remote \- manage set of tracked repositories
.SH "SYNOPSIS"
.sp
.nf
\fIgit\-remote\fR
\fIgit\-remote\fR add <name> <url>
\fIgit\-remote\fR show <name>
.fi
.SH "DESCRIPTION"
Manage the set of repositories ("remotes") whose branches you track.

With no arguments, shows a list of existing remotes.

In the second form, adds a remote named <name> for the repository at <url>. The command git fetch <name> can then be used to create and update remote\-tracking branches <name>/<branch>.

In the third form, gives some information about the remote <name>.

The remote configuration is achieved using the remote.origin.url and remote.origin.fetch configuration variables. (See \fBgit\-config\fR(1)).
.SH "EXAMPLES"
Add a new remote, fetch, and check out a branch from it:
.sp
.nf
$ git remote
origin
$ git branch \-r
origin/master
$ git remote add linux\-nfs git://linux\-nfs.org/pub/nfs\-2.6.git
$ git remote
linux\-nfs
origin
$ git fetch
* refs/remotes/linux\-nfs/master: storing branch 'master' ...
  commit: bf81b46
$ git branch \-r
origin/master
linux\-nfs/master
$ git checkout \-b nfs linux\-nfs/master
...
.fi
.SH "SEE ALSO"
\fBgit\-fetch\fR(1) \fBgit\-branch\fR(1) \fBgit\-config\fR(1)
.SH "AUTHOR"
Written by Junio Hamano
.SH "DOCUMENTATION"
Documentation by J. Bruce Fields and the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

