.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-INIT\-DB" "1" "01/08/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-init\-db \- Creates an empty git repository
.SH "SYNOPSIS"
\fIgit\-init\-db\fR [\-\-template=<template_directory>] [\-\-shared[=<permissions>]]
.SH "OPTIONS"
.TP
\-\-template=<template_directory>
Provide the directory from which templates will be used. The default template directory is /usr/share/git\-core/templates.

When specified, <template_directory> is used as the source of the template files rather than the default. The template files include some directory structure, some suggested "exclude patterns", and copies of non\-executing "hook" files. The suggested patterns and hook files are all modifiable and extensible.
.TP
\-\-shared[={false|true|umask|group|all|world|everybody}]
Specify that the git repository is to be shared amongst several users. This allows users belonging to the same group to push into that repository. When specified, the config variable "core.sharedRepository" is set so that files and directories under $GIT_DIR are created with the requested permissions. When not specified, git will use permissions reported by umask(2).

The option can have the following values, defaulting to \fIgroup\fR if no value is given:
.RS
.TP 3
\(bu
\fIumask\fR (or \fIfalse\fR): Use permissions reported by umask(2). The default, when \-\-shared is not specified.
.TP
\(bu
\fIgroup\fR (or \fItrue\fR): Make the repository group\-writable, (and g+sx, since the git group may be not the primary group of all users).
.TP
\(bu
\fIall\fR (or \fIworld\fR or \fIeverybody\fR): Same as \fIgroup\fR, but make the repository readable by all users.

By default, the configuration flag receive.denyNonFastforward is enabled in shared repositories, so that you cannot force a non fast\-forwarding push into it.
.RE
.SH "DESCRIPTION"
This command creates an empty git repository \- basically a .git directory with subdirectories for objects, refs/heads, refs/tags, and template files. An initial HEAD file that references the HEAD of the master branch is also created.

If the $GIT_DIR environment variable is set then it specifies a path to use instead of ./.git for the base of the repository.

If the object storage directory is specified via the $GIT_OBJECT_DIRECTORY environment variable then the sha1 directories are created underneath \- otherwise the default $GIT_DIR/objects directory is used.

Running git\-init\-db in an existing repository is safe. It will not overwrite things that are already there. The primary reason for rerunning git\-init\-db is to pick up newly added templates.

Note that git\-init is the same as git\-init\-db.
.SH "EXAMPLES"
.TP
Start a new git repository for an existing code base
.sp
.nf
$ cd /path/to/my/codebase
$ git\-init\-db   \fB(1)\fR
$ git\-add .     \fB(2)\fR
.fi
.sp
\fB1. \fRprepare /path/to/my/codebase/.git directory
.br
\fB2. \fRadd all existing file to the index
.br
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl.org>
.SH "DOCUMENTATION"
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

