.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-HELP" "1" "12/19/2007" "Git 1.5.4.rc0.73.gce85b" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-help \- display help information about git
.SH "SYNOPSIS"
\fIgit help\fR [\-a|\-\-all|\-i|\-\-info|\-m|\-\-man|\-w|\-\-web] [COMMAND]
.SH "DESCRIPTION"
With no options and no COMMAND given, the synopsis of the \fIgit\fR command and a list of the most commonly used git commands are printed on the standard output.

If the option \fI\-\-all\fR or \fI\-a\fR is given, then all available commands are printed on the standard output.

If a git command is named, a manual page for that command is brought up. The \fIman\fR program is used by default for this purpose, but this can be overridden by other options or configuration variables.

Note that \fIgit \-\-help \&...\fR is identical as \fIgit help \&...\fR because the former is internally converted into the latter.
.SH "OPTIONS"
.TP
\-a|\-\-all
Prints all the available commands on the standard output. This option supersedes any other option.
.TP
\-i|\-\-info
Use the \fIinfo\fR program to display the manual page, instead of the \fIman\fR program that is used by default.
.TP
\-m|\-\-man
Use the \fIman\fR program to display the manual page. This may be used to override a value set in the \fIhelp.format\fR configuration variable.
.TP
\-w|\-\-web
Use a web browser to display the HTML manual page, instead of the \fIman\fR program that is used by default.

The web browser can be specified using the configuration variable \fIhelp.browser\fR, or \fIweb.browser\fR if the former is not set. If none of these config variables is set, the \fIgit\-help\-\-browse\fR helper script (called by \fIgit\-help\fR) will pick a suitable default.

You can explicitly provide a full path to your preferred browser by setting the configuration variable \fIbrowser.<tool>.path\fR. For example, you can configure the absolute path to firefox by setting \fIbrowser.firefox.path\fR. Otherwise, \fIgit\-help\-\-browse\fR assumes the tool is available in PATH.

Note that the script tries, as much as possible, to display the HTML page in a new tab on an already opened browser.
.SH "CONFIGURATION VARIABLES"
If no command line option is passed, the \fIhelp.format\fR configuration variable will be checked. The following values are supported for this variable; they make \fIgit\-help\fR behave as their corresponding command line option:
.TP 3
\(bu
"man" corresponds to \fI\-m|\-\-man\fR,
.TP
\(bu
"info" corresponds to \fI\-i|\-\-info\fR,
.TP
\(bu
"web" or "html" correspond to \fI\-w|\-\-web\fR,

The \fIhelp.browser\fR, \fIweb.browser\fR and \fIbrowser.<tool>.path\fR will also be checked if the \fIweb\fR format is chosen (either by command line option or configuration variable). See \fI\-w|\-\-web\fR in the OPTIONS section above.

Note that these configuration variables should probably be set using the \fI\-\-global\fR flag, for example like this:
.sp
.nf
.ft C
$ git config \-\-global help.format web
$ git config \-\-global web.browser firefox
.ft

.fi
as they are probably more user specific than repository specific. See \fBgit\-config\fR(1) for more information about this.
.SH "AUTHOR"
Written by Junio C Hamano <gitster@pobox.com> and the git\-list <git@vger.kernel.org>.
.SH "DOCUMENTATION"
Initial documentation was part of the \fBgit\fR(7) man page. Christian Couder <chriscool@tuxfamily.org> extracted and rewrote it a little. Maintenance is done by the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

