.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-SHOW" "1" "10/03/2006" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-show \- Show one commit with difference it introduces
.SH "SYNOPSIS"
\fIgit\-show\fR <option>\&...
.sp
.SH "DESCRIPTION"
Shows commit log and textual diff for a single commit. The command internally invokes \fIgit\-rev\-list\fR piped to \fIgit\-diff\-tree\fR, and takes command line options for both of these commands. It also presents the merge commit in a special format as produced by \fIgit\-diff\-tree \-\-cc\fR.
.sp
This manual page describes only the most frequently used options.
.sp
.SH "OPTIONS"
.TP
<commitid>
ID of the commit to show.
.TP
\-\-pretty=<format>
Controls the output format for the commit logs. <format> can be one of
\fIraw\fR,
\fImedium\fR,
\fIshort\fR,
\fIfull\fR, and
\fIoneline\fR.
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl.org> and Junio C Hamano <junkio@cox.net>
.sp
.SH "DOCUMENTATION"
Documentation by David Greaves, Petr Baudis and the git\-list <git@vger.kernel.org>.
.sp
This manual page is a stub. You can help the git documentation by expanding it.
.sp
.SH "GIT"
Part of the \fBgit\fR(7) suite
.sp
