.\"     Title: git-cherry-pick
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 07/01/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.2.rc0.64.ge9cc0
.\"
.TH "GIT\-CHERRY\-PICK" "1" "07/01/2009" "Git 1\.6\.2\.rc0\.64\.ge9cc0" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-cherry-pick - Apply the change introduced by an existing commit
.SH "SYNOPSIS"
\fIgit cherry\-pick\fR [\-\-edit] [\-n] [\-m parent\-number] [\-s] [\-x] <commit>
.sp
.SH "DESCRIPTION"
Given one existing commit, apply the change the patch introduces, and record a new commit that records it\. This requires your working tree to be clean (no modifications from the HEAD commit)\.
.sp
.SH "OPTIONS"
.PP
<commit>
.RS 4
Commit to cherry\-pick\. For a more complete list of ways to spell commits, see the "SPECIFYING REVISIONS" section in
\fBgit-rev-parse\fR(1)\.
.RE
.PP
\-e, \-\-edit
.RS 4
With this option,
\fIgit\-cherry\-pick\fR
will let you edit the commit message prior to committing\.
.RE
.PP
\-x
.RS 4
When recording the commit, append to the original commit message a note that indicates which commit this change was cherry\-picked from\. Append the note only for cherry picks without conflicts\. Do not use this option if you are cherry\-picking from your private branch because the information is useless to the recipient\. If on the other hand you are cherry\-picking between two publicly visible branches (e\.g\. backporting a fix to a maintenance branch for an older release from a development branch), adding this information can be useful\.
.RE
.PP
\-r
.RS 4
It used to be that the command defaulted to do
\-x
described above, and
\-r
was to disable it\. Now the default is not to do
\-x
so this option is a no\-op\.
.RE
.PP
\-m parent\-number, \-\-mainline parent\-number
.RS 4
Usually you cannot cherry\-pick a merge because you do not know which side of the merge should be considered the mainline\. This option specifies the parent number (starting from 1) of the mainline and allows cherry\-pick to replay the change relative to the specified parent\.
.RE
.PP
\-n, \-\-no\-commit
.RS 4
Usually the command automatically creates a commit\. This flag applies the change necessary to cherry\-pick the named commit to your working tree and the index, but does not make the commit\. In addition, when this option is used, your index does not have to match the HEAD commit\. The cherry\-pick is done against the beginning state of your index\.
.sp
This is useful when cherry\-picking more than one commits\' effect to your index in a row\.
.RE
.PP
\-s, \-\-signoff
.RS 4
Add Signed\-off\-by line at the end of the commit message\.
.RE
.SH "AUTHOR"
Written by Junio C Hamano <gitster@pobox\.com>
.sp
.SH "DOCUMENTATION"
Documentation by Junio C Hamano and the git\-list <git@vger\.kernel\.org>\.
.sp
.SH "GIT"
Part of the \fBgit\fR(1) suite
.sp
