.\"     Title: git-web--browse
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 04/02/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.2.rc0.64.ge9cc0
.\"
.TH "GIT\-WEB\-\-BROWSE" "1" "04/02/2009" "Git 1\.6\.2\.rc0\.64\.ge9cc0" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-web--browse - git helper script to launch a web browser
.SH "SYNOPSIS"
\fIgit web\-\-browse\fR [OPTIONS] URL/FILE \&...
.sp
.SH "DESCRIPTION"
This script tries, as much as possible, to display the URLs and FILEs that are passed as arguments, as HTML pages in new tabs on an already opened web browser\.
.sp
The following browsers (or commands) are currently supported:
.sp
.sp
.RS 4
\h'-04'\(bu\h'+03'firefox (this is the default under X Window when not using KDE)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'iceweasel
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'konqueror (this is the default under KDE, see
\fINote about konqueror\fR
below)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'w3m (this is the default outside graphical environments)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'links
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'lynx
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'dillo
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'open (this is the default under Mac OS X GUI)
.RE
.sp
.RS 4
\h'-04'\(bu\h'+03'start (this is the default under MinGW)
.RE
Custom commands may also be specified\.
.sp
.SH "OPTIONS"
.PP
\-b BROWSER, \-\-browser=BROWSER
.RS 4
Use the specified BROWSER\. It must be in the list of supported browsers\.
.RE
.PP
\-t BROWSER, \-\-tool=BROWSER
.RS 4
Same as above\.
.RE
.PP
\-c CONF\.VAR, \-\-config=CONF\.VAR
.RS 4
CONF\.VAR is looked up in the git config files\. If it\'s set, then its value specify the browser that should be used\.
.RE
.SH "CONFIGURATION VARIABLES"
.SS "CONF\.VAR (from \-c option) and web\.browser"
The web browser can be specified using a configuration variable passed with the \-c (or \-\-config) command line option, or the \fIweb\.browser\fR configuration variable if the former is not used\.
.sp
.SS "browser\.<tool>\.path"
You can explicitly provide a full path to your preferred browser by setting the configuration variable \fIbrowser\.<tool>\.path\fR\. For example, you can configure the absolute path to firefox by setting \fIbrowser\.firefox\.path\fR\. Otherwise, \fIgit\-web\-\-browse\fR assumes the tool is available in PATH\.
.sp
.SS "browser\.<tool>\.cmd"
When the browser, specified by options or configuration variables, is not among the supported ones, then the corresponding \fIbrowser\.<tool>\.cmd\fR configuration variable will be looked up\. If this variable exists then \fIgit\-web\-\-browse\fR will treat the specified tool as a custom command and will use a shell eval to run the command with the URLs passed as arguments\.
.sp
.SH "NOTE ABOUT KONQUEROR"
When \fIkonqueror\fR is specified by a command line option or a configuration variable, we launch \fIkfmclient\fR to try to open the HTML man page on an already opened konqueror in a new tab if possible\.
.sp
For consistency, we also try such a trick if \fIbrowser\.konqueror\.path\fR is set to something like \fIA_PATH_TO/konqueror\fR\. That means we will try to launch \fIA_PATH_TO/kfmclient\fR instead\.
.sp
If you really want to use \fIkonqueror\fR, then you can use something like the following:
.sp
.sp
.RS 4
.nf

\.ft C
        [web]
                browser = konq

        [browser "konq"]
                cmd = A_PATH_TO/konqueror
\.ft

.fi
.RE
.SS "Note about git\-config \-\-global"
Note that these configuration variables should probably be set using the \fI\-\-global\fR flag, for example like this:
.sp
.sp
.RS 4
.nf

\.ft C
$ git config \-\-global web\.browser firefox
\.ft

.fi
.RE
as they are probably more user specific than repository specific\. See \fBgit-config\fR(1) for more information about this\.
.sp
.SH "AUTHOR"
Written by Christian Couder <chriscool@tuxfamily\.org> and the git\-list <git@vger\.kernel\.org>, based on \fIgit\-mergetool\fR by Theodore Y\. Ts\'o\.
.sp
.SH "DOCUMENTATION"
Documentation by Christian Couder <chriscool@tuxfamily\.org> and the git\-list <git@vger\.kernel\.org>\.
.sp
.SH "GIT"
Part of the \fBgit\fR(1) suite
.sp
