.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-MERGE\-ONE\-FILE" "1" "01/19/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-merge\-one\-file \- The standard helper program to use with git\-merge\-index
.SH "SYNOPSIS"
\fIgit\-merge\-one\-file\fR
.SH "DESCRIPTION"
This is the standard helper program to use with "git\-merge\-index" to resolve a merge after the trivial merge done with "git\-read\-tree \-m".
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl.org>, Junio C Hamano <junkio@cox.net> and Petr Baudis <pasky@suse.cz>.
.SH "DOCUMENTATION"
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

