.\"     Title: git-upload-archive
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 09/19/2008
.\"    Manual: Git Manual
.\"    Source: Git 1.6.0.2.287.g3791f
.\"
.TH "GIT\-UPLOAD\-ARCHIVE" "1" "09/19/2008" "Git 1\.6\.0\.2\.287\.g3791f" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-upload-archive - Send archive back to git-archive
.SH "SYNOPSIS"
\fIgit upload\-archive\fR <directory>
.SH "DESCRIPTION"
Invoked by \fIgit\-archive \-\-remote\fR and sends a generated archive to the other end over the git protocol\.

This command is usually not invoked directly by the end user\. The UI for the protocol is on the \fIgit\-archive\fR side, and the program pair is meant to be used to get an archive from a remote repository\.
.SH "OPTIONS"
.PP
<directory>
.RS 4
The repository to get a tar archive from\.
.RE
.SH "AUTHOR"
Written by Franck Bui\-Huu\.
.SH "DOCUMENTATION"
Documentation by Junio C Hamano and the git\-list <git@vger\.kernel\.org>\.
.SH "GIT"
Part of the \fBgit\fR(1) suite

