.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-ADD" "1" "12/13/2006" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-add \- Add file contents to the changeset to be committed next
.SH "SYNOPSIS"
\fIgit\-add\fR [\-n] [\-v] [\-\-] <file>\&...
.SH "DESCRIPTION"
All the changed file contents to be committed together in a single set of changes must be "added" with the \fIadd\fR command before using the \fIcommit\fR command. This is not only for adding new files. Even modified files must be added to the set of changes about to be committed.

This command can be performed multiple times before a commit. The added content corresponds to the state of specified file(s) at the time the \fIadd\fR command is used. This means the \fIcommit\fR command will not consider subsequent changes to already added content if it is not added again before the commit.

The \fIgit status\fR command can be used to obtain a summary of what is included for the next commit.

This command only adds non\-ignored files, to add ignored files use "git update\-index \-\-add".

Please see \fBgit\-commit\fR(1) for alternative ways to add content to a commit.
.SH "OPTIONS"
.TP
<file>\&...
Files to add content from.
.TP
\-n
Don't actually add the file(s), just show if they exist.
.TP
\-v
Be verbose.
.TP
\-\-
This option can be used to separate command\-line options from the list of files, (useful when filenames might be mistaken for command\-line options).
.SH "EXAMPLES"
.TP
git\-add Documentation/\\*.txt
Adds content from all *.txt files under Documentation directory and its subdirectories.

Note that the asterisk * is quoted from the shell in this example; this lets the command to include the files from subdirectories of Documentation/ directory.
.TP
git\-add git\-*.sh
Considers adding content from all git\-*.sh scripts. Because this example lets shell expand the asterisk (i.e. you are listing the files explicitly), it does not consider subdir/git\-foo.sh.
.SH "SEE ALSO"
\fBgit\-status\fR(1) \fBgit\-rm\fR(1) \fBgit\-mv\fR(1) \fBgit\-commit\fR(1) \fBgit\-update\-index\fR(1)
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl.org>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano and the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

