.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-REFLOG" "1" "01/16/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-reflog \- Manage reflog information
.SH "SYNOPSIS"
.sp
.nf
\fIgit\-reflog\fR expire [\-\-dry\-run] [\-\-stale\-fix]
        [\-\-expire=<time>] [\-\-expire\-unreachable=<time>] [\-\-all] <refs>\&...
.fi
.SH "DESCRIPTION"
Reflog is a mechanism to record when the tip of branches are updated. This command is to manage the information recorded in it.

The subcommand "expire" is used to prune older reflog entries. Entries older than expire time, or entries older than expire\-unreachable time and are not reachable from the current tip, are removed from the reflog. This is typically not used directly by the end users \(em instead, see \fBgit\-gc\fR(1).
.SH "OPTIONS"
.TP
\-\-expire=<time>
Entries older than this time are pruned. Without the option it is taken from configuration gc.reflogExpire, which in turn defaults to 90 days.
.TP
\-\-expire\-unreachable=<time>
Entries older than this time and are not reachable from the current tip of the branch are pruned. Without the option it is taken from configuration gc.reflogExpireUnreachable, which in turn defaults to 30 days.
.TP
\-\-all
Instead of listing <refs> explicitly, prune all refs.
.SH "AUTHOR"
Written by Junio C Hamano <junkio@cox.net>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano and the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

