'\" t
.\"     Title: git-mv
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.74.3 <http://docbook.sf.net/>
.\"      Date: 11/15/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.5.2.185.gb7fba
.\"  Language: English
.\"
.TH "GIT\-MV" "1" "11/15/2009" "Git 1\&.6\&.5\&.2\&.185\&.gb7f" "Git Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-mv \- Move or rename a file, a directory, or a symlink
.SH "SYNOPSIS"
.sp
\fIgit mv\fR <options>\&... <args>\&...
.SH "DESCRIPTION"
.sp
This script is used to move or rename a file, directory or symlink\&.
.sp
.if n \{\
.RS 4
.\}
.nf
git mv [\-f] [\-n] <source> <destination>
git mv [\-f] [\-n] [\-k] <source> \&.\&.\&. <destination directory>
.fi
.if n \{\
.RE
.\}
.sp
In the first form, it renames <source>, which must exist and be either a file, symlink or directory, to <destination>\&. In the second form, the last argument has to be an existing directory; the given sources will be moved into this directory\&.
.sp
The index is updated after successful completion, but the change must still be committed\&.
.SH "OPTIONS"
.PP
\-f, \-\-force
.RS 4
Force renaming or moving of a file even if the target exists
.RE
.PP
\-k
.RS 4
Skip move or rename actions which would lead to an error condition\&. An error happens when a source is neither existing nor controlled by GIT, or when it would overwrite an existing file unless
\fI\-f\fR
is given\&.
.RE
.PP
\-n, \-\-dry\-run
.RS 4
Do nothing; only show what would happen
.RE
.SH "AUTHOR"
.sp
Written by Linus Torvalds <torvalds@osdl\&.org> Rewritten by Ryan Anderson <ryan@michonline\&.com> Move functionality added by Josef Weidendorfer <Josef\&.Weidendorfer@gmx\&.de>
.SH "DOCUMENTATION"
.sp
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger\&.kernel\&.org>\&.
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
