.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-FMT\-MERGE\-MSG" "1" "10/03/2006" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-fmt\-merge\-msg \- Produce a merge commit message
.SH "SYNOPSIS"
\fIgit\-fmt\-merge\-msg\fR <$GIT_DIR/FETCH_HEAD
.sp
.SH "DESCRIPTION"
Takes the list of merged objects on stdin and produces a suitable commit message to be used for the merge commit, usually to be passed as the \fI<merge\-message>\fR argument of git\-merge.
.sp
This script is intended mostly for internal use by scripts automatically invoking git\-merge.
.sp
.SH "SEE ALSO"
\fBgit\-merge\fR(1)
.sp
.SH "AUTHOR"
Written by Junio C Hamano <junkio@cox.net>
.sp
.SH "DOCUMENTATION"
Documentation by Petr Baudis, Junio C Hamano and the git\-list <git@vger.kernel.org>.
.sp
.SH "GIT"
Part of the \fBgit\fR(7) suite
.sp
