.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-CAT\-FILE" "1" "07/19/2007" "Git 1.5.3.rc2.19.gc4fba" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-cat\-file \- Provide content or type/size information for repository objects
.SH "SYNOPSIS"
\fIgit\-cat\-file\fR [\-t | \-s | \-e | \-p | <type>] <object>
.SH "DESCRIPTION"
Provides content or type of objects in the repository. The type is required unless \fI\-t\fR or \fI\-p\fR is used to find the object type, or \fI\-s\fR is used to find the object size.
.SH "OPTIONS"
.TP
<object>
The name of the object to show. For a more complete list of ways to spell object names, see "SPECIFYING REVISIONS" section in \fBgit\-rev\-parse\fR(1).
.TP
\-t
Instead of the content, show the object type identified by <object>.
.TP
\-s
Instead of the content, show the object size identified by <object>.
.TP
\-e
Suppress all output; instead exit with zero status if <object> exists and is a valid object.
.TP
\-p
Pretty\-print the contents of <object> based on its type.
.TP
<type>
Typically this matches the real type of <object> but asking for a type that can trivially be dereferenced from the given <object> is also permitted. An example is to ask for a "tree" with <object> being a commit object that contains it, or to ask for a "blob" with <object> being a tag object that points at it.
.SH "OUTPUT"
If \fI\-t\fR is specified, one of the <type>.

If \fI\-s\fR is specified, the size of the <object> in bytes.

If \fI\-e\fR is specified, no output.

If \fI\-p\fR is specified, the contents of <object> are pretty\-printed.

Otherwise the raw (though uncompressed) contents of the <object> will be returned.
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl.org>
.SH "DOCUMENTATION"
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

