'\" t
.\"     Title: git-shell
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 07/21/2010
.\"    Manual: Git Manual
.\"    Source: Git 1.7.2
.\"  Language: English
.\"
.TH "GIT\-SHELL" "1" "07/21/2010" "Git 1\&.7\&.2" "Git Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-shell \- Restricted login shell for GIT\-only SSH access
.SH "SYNOPSIS"
.sp
\fI$(git \-\-exec\-path)/git\-shell\fR \-c <command> <argument>
.SH "DESCRIPTION"
.sp
This is meant to be used as a login shell for SSH accounts you want to restrict to GIT pull/push access only\&. It permits execution only of server\-side GIT commands implementing the pull/push functionality\&. The commands can be executed only by the \fI\-c\fR option; the shell is not interactive\&.
.sp
Currently, only four commands are permitted to be called, \fIgit\-receive\-pack\fR \fIgit\-upload\-pack\fR and \fIgit\-upload\-archive\fR with a single required argument, or \fIcvs server\fR (to invoke \fIgit\-cvsserver\fR)\&.
.SH "AUTHOR"
.sp
Written by Linus Torvalds <torvalds@osdl\&.org>
.SH "DOCUMENTATION"
.sp
Documentation by Petr Baudis and the git\-list <git@vger\&.kernel\&.org>\&.
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
