'\" t
.\"     Title: git-stripspace
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 09/03/2010
.\"    Manual: Git Manual
.\"    Source: Git 1.7.2
.\"  Language: English
.\"
.TH "GIT\-STRIPSPACE" "1" "09/03/2010" "Git 1\&.7\&.2" "Git Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-stripspace \- Filter out empty lines
.SH "SYNOPSIS"
.sp
\fIgit stripspace\fR [\-s | \-\-strip\-comments] < <stream>
.SH "DESCRIPTION"
.sp
Remove multiple empty lines, and empty lines at beginning and end\&.
.SH "OPTIONS"
.PP
\-s, \-\-strip\-comments
.RS 4
In addition to empty lines, also strip lines starting with
\fI#\fR\&.
.RE
.PP
<stream>
.RS 4
Byte stream to act on\&.
.RE
.SH "AUTHOR"
.sp
Written by Linus Torvalds <torvalds@osdl\&.org>
.SH "DOCUMENTATION"
.sp
Documentation by Junio C Hamano and the git\-list <git@vger\&.kernel\&.org>\&.
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
