'\" t
.\"     Title: git-last-modified
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 2025-09-29
.\"    Manual: Git Manual
.\"    Source: Git 2.51.0.372.g821f583da6
.\"  Language: English
.\"
.TH "GIT\-LAST\-MODIFIED" "1" "2025-09-29" "Git 2\&.51\&.0\&.372\&.g821f58" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-last-modified \- EXPERIMENTAL: Show when files were last modified
.SH "SYNOPSIS"
.sp
.nf
\fBgit\fR \fBlast\-modified\fR [\fB\-\-recursive\fR] [\fB\-\-show\-trees\fR] [\fI<revision\-range>\fR] [[\fB\-\-\fR] \fI<path>\fR\&...\:]
.fi
.SH "DESCRIPTION"
.sp
Shows which commit last modified each of the relevant files and subdirectories\&. A commit renaming a path, or changing it\(cqs mode is also taken into account\&.
.sp
THIS COMMAND IS EXPERIMENTAL\&. THE BEHAVIOR MAY CHANGE\&.
.SH "OPTIONS"
.PP
\fB\-r\fR, \fB\-\-recursive\fR
.RS 4
Instead of showing tree entries, step into subtrees and show all entries inside them recursively\&.
.RE
.PP
\fB\-t\fR, \fB\-\-show\-trees\fR
.RS 4
Show tree entries even when recursing into them\&. It has no effect without
\fB\-\-recursive\fR\&.
.RE
.PP
\fI<revision\-range>\fR
.RS 4
Only traverse commits in the specified revision range\&. When no
\fI<revision\-range>\fR
is specified, it defaults to
\fBHEAD\fR
(i\&.e\&. the whole history leading to the current commit)\&. For a complete list of ways to spell
\fI<revision\-range>\fR, see the
\fISpecifying Ranges\fR
section of
\fBgitrevisions\fR(7)\&.
.RE
.PP
[\fB\-\-\fR] \fI<path>\fR\&.\&.\&.
.RS 4
For each
\fI<path>\fR
given, the commit which last modified it is returned\&. Without an optional path parameter, all files and subdirectories in path traversal the are included in the output\&.
.RE
.SH "SEE ALSO"
.sp
\fBgit-blame\fR(1), \fBgit-log\fR(1)\&.
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
