.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-STATUS" "1" "01/19/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-status \- Show the working tree status
.SH "SYNOPSIS"
\fIgit\-status\fR <options>\&...
.SH "DESCRIPTION"
Examines paths in the working tree that has changes unrecorded to the index file, and changes between the index file and the current HEAD commit. The former paths are what you _could_ commit by running \fIgit\-update\-index\fR before running \fIgit commit\fR, and the latter paths are what you _would_ commit by running \fIgit commit\fR.

If there is no path that is different between the index file and the current HEAD commit, the command exits with non\-zero status.

The command takes the same set of options as git\-commit; it shows what would be committed if the same options are given to git\-commit.
.SH "OUTPUT"
The output from this command is designed to be used as a commit template comments, and all the output lines are prefixed with \fI#\fR.
.SH "CONFIGURATION"
The command honors color.status (or status.color \(em they mean the same thing and the latter is kept for backward compatibility) and color.status.<slot> configuration variables to colorize its output.
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl.org> and Junio C Hamano <junkio@cox.net>.
.SH "DOCUMENTATION"
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

