.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-REQUEST\-PULL" "1" "06/02/2007" "Git 1.5.2.167.g4bc70" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-request\-pull \- Generates a summary of pending changes
.SH "SYNOPSIS"
\fIgit\-request\-pull\fR <start> <url> [<end>]
.SH "DESCRIPTION"
Summarizes the changes between two commits to the standard output, and includes the given URL in the generated summary.
.SH "OPTIONS"
.TP
<start>
Commit to start at.
.TP
<url>
URL to include in the summary.
.TP
<end>
Commit to send at; defaults to HEAD.
.SH "AUTHOR"
Written by Ryan Anderson <ryan@michonline.com> and Junio C Hamano <junkio@cox.net>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano and the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

