'\" t
.\"     Title: git-shell
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 12/02/2011
.\"    Manual: Git Manual
.\"    Source: Git 1.7.8
.\"  Language: English
.\"
.TH "GIT\-SHELL" "1" "12/02/2011" "Git 1\&.7\&.8" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-shell \- Restricted login shell for Git\-only SSH access
.SH "SYNOPSIS"
.sp
.nf
\fIgit shell\fR [\-c <command> <argument>]
.fi
.sp
.SH "DESCRIPTION"
.sp
A login shell for SSH accounts to provide restricted Git access\&. When \fI\-c\fR is given, the program executes <command> non\-interactively; <command> can be one of \fIgit receive\-pack\fR, \fIgit upload\-pack\fR, \fIgit upload\-archive\fR, \fIcvs server\fR, or a command in COMMAND_DIR\&. The shell is started in interactive mode when no arguments are given; in this case, COMMAND_DIR must exist, and any of the executables in it can be invoked\&.
.sp
\fIcvs server\fR is a special command which executes git\-cvsserver\&.
.sp
COMMAND_DIR is the path "$HOME/git\-shell\-commands"\&. The user must have read and execute permissions to the directory in order to execute the programs in it\&. The programs are executed with a cwd of $HOME, and <argument> is parsed as a command\-line string\&.
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
