'\" t
.\"     Title: git-verify-pack
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 2025-09-08
.\"    Manual: Git Manual
.\"    Source: Git 2.51.0.193.g4975ec3473
.\"  Language: English
.\"
.TH "GIT\-VERIFY\-PACK" "1" "2025-09-08" "Git 2\&.51\&.0\&.193\&.g4975ec" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-verify-pack \- Validate packed Git archive files
.SH "SYNOPSIS"
.sp
.nf
\fBgit\fR \fBverify\-pack\fR [\fB\-v\fR | \fB\-\-verbose\fR] [\fB\-s\fR | \fB\-\-stat\-only\fR] [\fB\-\-\fR] \fI<pack>\fR\&.idx\&...\:
.fi
.SH "DESCRIPTION"
.sp
Read each idx file for packed Git archive given on the command line, and verify the idx file and the corresponding pack file\&.
.SH "OPTIONS"
.PP
\fB\-v\fR, \fB\-\-verbose\fR
.RS 4
After verifying the pack, show the list of objects contained in the pack and a histogram of delta chain length\&.
.RE
.PP
\fB\-s\fR, \fB\-\-stat\-only\fR
.RS 4
Do not verify the pack contents; only show the histogram of delta chain length\&. With
\fB\-\-verbose\fR, the list of objects is also shown\&.
.RE
.PP
\fB\-\-\fR
.RS 4
Do not interpret any more arguments as options\&.
.RE
.SH "OUTPUT FORMAT"
.sp
When specifying the \fB\-v\fR option the format used is:
.sp
.if n \{\
.RS 4
.\}
.nf
object\-name type size size\-in\-packfile offset\-in\-packfile
.fi
.if n \{\
.RE
.\}
.sp
for objects that are not deltified in the pack, and
.sp
.if n \{\
.RS 4
.\}
.nf
object\-name type size size\-in\-packfile offset\-in\-packfile depth base\-object\-name
.fi
.if n \{\
.RE
.\}
.sp
for objects that are deltified\&.
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
