'\" t
.\"     Title: git-rm
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 12/02/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.6.rc1
.\"  Language: English
.\"
.TH "GIT\-RM" "1" "12/02/2009" "Git 1\&.6\&.6\&.rc1" "Git Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-rm \- Remove files from the working tree and from the index
.SH "SYNOPSIS"
.sp
\fIgit rm\fR [\-f | \-\-force] [\-n] [\-r] [\-\-cached] [\-\-ignore\-unmatch] [\-\-quiet] [\-\-] <file>\&...
.SH "DESCRIPTION"
.sp
Remove files from the index, or from the working tree and the index\&. \fIgit\-rm\fR will not remove a file from just your working directory\&. (There is no option to remove a file only from the work tree and yet keep it in the index; use /bin/rm if you want to do that\&.) The files being removed have to be identical to the tip of the branch, and no updates to their contents can be staged in the index, though that default behavior can be overridden with the \-f option\&. When \fI\-\-cached\fR is given, the staged content has to match either the tip of the branch or the file on disk, allowing the file to be removed from just the index\&.
.SH "OPTIONS"
.PP
<file>\&...
.RS 4
Files to remove\&. Fileglobs (e\&.g\&.
*\&.c) can be given to remove all matching files\&. If you want git to expand file glob characters, you may need to shell\-escape them\&. A leading directory name (e\&.g\&.
dir
to remove
dir/file1
and
dir/file2) can be given to remove all files in the directory, and recursively all sub\-directories, but this requires the
\-r
option to be explicitly given\&.
.RE
.PP
\-f, \-\-force
.RS 4
Override the up\-to\-date check\&.
.RE
.PP
\-n, \-\-dry\-run
.RS 4
Don\(aqt actually remove any file(s)\&. Instead, just show if they exist in the index and would otherwise be removed by the command\&.
.RE
.PP
\-r
.RS 4
Allow recursive removal when a leading directory name is given\&.
.RE
.PP
\-\-
.RS 4
This option can be used to separate command\-line options from the list of files, (useful when filenames might be mistaken for command\-line options)\&.
.RE
.PP
\-\-cached
.RS 4
Use this option to unstage and remove paths only from the index\&. Working tree files, whether modified or not, will be left alone\&.
.RE
.PP
\-\-ignore\-unmatch
.RS 4
Exit with a zero status even if no files matched\&.
.RE
.PP
\-q, \-\-quiet
.RS 4

\fIgit\-rm\fR
normally outputs one line (in the form of an "rm" command) for each file removed\&. This option suppresses that output\&.
.RE
.SH "DISCUSSION"
.sp
The <file> list given to the command can be exact pathnames, file glob patterns, or leading directory names\&. The command removes only the paths that are known to git\&. Giving the name of a file that you have not told git about does not remove that file\&.
.sp
File globbing matches across directory boundaries\&. Thus, given two directories d and d2, there is a difference between using git rm \(aqd*\(aq and git rm \(aqd/*\(aq, as the former will also remove all of directory d2\&.
.SH "EXAMPLES"
.PP
git rm Documentation/\e*\&.txt
.RS 4
Removes all
*\&.txt
files from the index that are under the
Documentation
directory and any of its subdirectories\&.
.sp
Note that the asterisk
*
is quoted from the shell in this example; this lets git, and not the shell, expand the pathnames of files and subdirectories under the
Documentation/
directory\&.
.RE
.PP
git rm \-f git\-*\&.sh
.RS 4
Because this example lets the shell expand the asterisk (i\&.e\&. you are listing the files explicitly), it does not remove
subdir/git\-foo\&.sh\&.
.RE
.SH "SEE ALSO"
.sp
\fBgit-add\fR(1)
.SH "AUTHOR"
.sp
Written by Linus Torvalds <torvalds@osdl\&.org>
.SH "DOCUMENTATION"
.sp
Documentation by Junio C Hamano and the git\-list <git@vger\&.kernel\&.org>\&.
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
