.\"     Title: git-show-index
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 10/31/2008
.\"    Manual: Git Manual
.\"    Source: Git 1.6.0.2.287.g3791f
.\"
.TH "GIT\-SHOW\-INDEX" "1" "10/31/2008" "Git 1\.6\.0\.2\.287\.g3791f" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-show-index - Show packed archive index
.SH "SYNOPSIS"
\fIgit show\-index\fR < idx\-file
.SH "DESCRIPTION"
Reads given idx file for packed git archive created with \fIgit\-pack\-objects\fR command, and dumps its contents\.

The information it outputs is subset of what you can get from \fIgit\-verify\-pack \-v\fR; this command only shows the packfile offset and SHA1 of each object\.
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl\.org>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano
.SH "GIT"
Part of the \fBgit\fR(1) suite

