'\" t
.\"     Title: git-tag
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 2025-11-16
.\"    Manual: Git Manual
.\"    Source: Git 2.52.0.rc2.22.gc93f1a0fa3
.\"  Language: English
.\"
.TH "GIT\-TAG" "1" "2025-11-16" "Git 2\&.52\&.0\&.rc2\&.22\&.gc" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-tag \- Create, list, delete or verify tags
.SH "SYNOPSIS"
.sp
.nf
\fBgit\fR \fBtag\fR [\fB\-a\fR | \fB\-s\fR | \fB\-u\fR \fI<key\-id>\fR] [\fB\-f\fR] [\fB\-m\fR \fI<msg>\fR | \fB\-F\fR \fI<file>\fR] [\fB\-e\fR]
	[(\fB\-\-trailer\fR \fI<token>\fR[(\fB=\fR|\fB:\fR)\fI<value>\fR])\&...\:]
	\fI<tagname>\fR [\fI<commit>\fR | \fI<object>\fR]
\fBgit\fR \fBtag\fR \fB\-d\fR \fI<tagname>\fR\&...\:
\fBgit\fR \fBtag\fR [\fB\-n\fR[\fI<num>\fR]] \fB\-l\fR [\fB\-\-contains\fR \fI<commit>\fR] [\fB\-\-no\-contains\fR \fI<commit>\fR]
	[\fB\-\-points\-at\fR \fI<object>\fR] [\fB\-\-column\fR[\fB=\fR\fI<options>\fR] | \fB\-\-no\-column\fR]
	[\fB\-\-create\-reflog\fR] [\fB\-\-sort=\fR\fI<key>\fR] [\fB\-\-format=\fR\fI<format>\fR]
	[\fB\-\-merged\fR \fI<commit>\fR] [\fB\-\-no\-merged\fR \fI<commit>\fR] [\fI<pattern>\fR\&...\:]
\fBgit\fR \fBtag\fR \fB\-v\fR [\fB\-\-format=\fR\fI<format>\fR] \fI<tagname>\fR\&...\:
.fi
.SH "DESCRIPTION"
.sp
Add a tag reference in \fBrefs/tags/\fR, unless \fB\-d\fR/\fB\-l\fR/\fB\-v\fR is given to delete, list or verify tags\&.
.sp
Unless \fB\-f\fR is given, the named tag must not yet exist\&.
.sp
If one of \fB\-a\fR, \fB\-s\fR, or \fB\-u\fR \fI<key\-id>\fR is passed, the command creates a \fItag\fR object, and requires a tag message\&. Unless \fB\-m\fR \fI<msg>\fR or \fB\-F\fR \fI<file>\fR is given, an editor is started for the user to type in the tag message\&.
.sp
If \fB\-m\fR \fI<msg>\fR or \fB\-F\fR \fI<file>\fR or \fB\-\-trailer\fR \fI<token>\fR[\fB=\fR\fI<value>\fR] is given and \fB\-a\fR, \fB\-s\fR, and \fB\-u\fR \fI<key\-id>\fR are absent, \fB\-a\fR is implied\&.
.sp
Otherwise, a tag reference that points directly at the given object (i\&.e\&., a lightweight tag) is created\&.
.sp
A cryptographically signed tag object will be created when \fB\-s\fR or \fB\-u\fR \fI<key\-id>\fR is used\&. The signing backend (GPG, X\&.509, SSH, etc\&.) is controlled by the \fBgpg\&.format\fR configuration variable, defaulting to OpenPGP\&. When \fB\-u\fR \fI<key\-id>\fR is not used, the committer identity for the current user is used to find the key for signing\&. The configuration variable \fBgpg\&.program\fR is used to specify a custom signing binary\&.
.sp
Tag objects (created with \fB\-a\fR, \fB\-s\fR, or \fB\-u\fR) are called "annotated" tags; they contain a creation date, the tagger name and e\-mail, a tagging message, and an optional cryptographic signature\&. Whereas a "lightweight" tag is simply a name for an object (usually a commit object)\&.
.sp
Annotated tags are meant for release while lightweight tags are meant for private or temporary object labels\&. For this reason, some git commands for naming objects (like \fBgit\fR \fBdescribe\fR) will ignore lightweight tags by default\&.
.SH "OPTIONS"
.PP
\fB\-a\fR, \fB\-\-annotate\fR
.RS 4
Make an unsigned, annotated tag object
.RE
.PP
\fB\-s\fR, \fB\-\-sign\fR
.RS 4
Make a cryptographically signed tag, using the default signing key\&. The signing backend used depends on the
\fBgpg\&.format\fR
configuration variable\&. The default key is determined by the backend\&. For GPG, it\(cqs based on the committer\(cqs email address, while for SSH it may be a specific key file or agent identity\&. See
\fBgit-config\fR(1)\&.
.RE
.PP
\fB\-\-no\-sign\fR
.RS 4
Override
\fBtag\&.gpgSign\fR
configuration variable that is set to force each and every tag to be signed\&.
.RE
.PP
\fB\-u\fR \fI<key\-id>\fR, \fB\-\-local\-user=\fR\fI<key\-id>\fR
.RS 4
Make a cryptographically signed tag using the given key\&. The format of the <key\-id> and the backend used depend on the
\fBgpg\&.format\fR
configuration variable\&. See
\fBgit-config\fR(1)\&.
.RE
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
Replace an existing tag with the given name (instead of failing)
.RE
.PP
\fB\-d\fR, \fB\-\-delete\fR
.RS 4
Delete existing tags with the given names\&.
.RE
.PP
\fB\-v\fR, \fB\-\-verify\fR
.RS 4
Verify the cryptographic signature of the given tags\&.
.RE
.PP
\fB\-n\fR\fI<num>\fR
.RS 4
\fI<num>\fR
specifies how many lines from the annotation, if any, are printed when using
\fB\-l\fR\&. Implies
\fB\-\-list\fR\&.
.sp
The default is not to print any annotation lines\&. If no number is given to
\fB\-n\fR, only the first line is printed\&. If the tag is not annotated, the commit message is displayed instead\&.
.RE
.PP
\fB\-l\fR, \fB\-\-list\fR
.RS 4
List tags\&. With optional
\fI<pattern>\fR\&.\&.\&., e\&.g\&.
\fBgit\fR
\fBtag\fR
\fB\-\-list\fR
\*(Aqv\-*\*(Aq, list only the tags that match the pattern(s)\&.
.sp
Running
\fBgit\fR
\fBtag\fR
without arguments also lists all tags\&. The pattern is a shell wildcard (i\&.e\&., matched using
\fBfnmatch\fR(3))\&. Multiple patterns may be given; if any of them matches, the tag is shown\&.
.sp
This option is implicitly supplied if any other list\-like option such as
\fB\-\-contains\fR
is provided\&. See the documentation for each of those options for details\&.
.RE
.PP
\fB\-\-sort=\fR\fI<key>\fR
.RS 4
Sort based on the key given\&. Prefix
\fB\-\fR
to sort in descending order of the value\&. You may use the
\fB\-\-sort=\fR\fI<key>\fR
option multiple times, in which case the last
\fI<key>\fR
becomes the primary key\&. Also supports "\fBversion:refname\fR" or "\fBv:refname\fR" (tag names are treated as versions)\&. The "\fBversion:refname\fR" sort order can also be affected by the "\fBversionsort\&.suffix\fR" configuration variable\&. The keys supported are the same as those in
\fBgit\fR
\fBfor\-each\-ref\fR\&. Sort order defaults to the value configured for the
\fBtag\&.sort\fR
variable if it exists, or lexicographic order otherwise\&. See
\fBgit-config\fR(1)\&.
.RE
.PP
\fB\-\-color\fR[\fB=\fR\fI<when>\fR]
.RS 4
Respect any colors specified in the
\fB\-\-format\fR
option\&. The
\fI<when>\fR
field must be one of
\fBalways\fR,
\fBnever\fR, or
\fBauto\fR
(if
\fI<when>\fR
is absent, behave as if
\fBalways\fR
was given)\&.
.RE
.PP
\fB\-i\fR, \fB\-\-ignore\-case\fR
.RS 4
Sorting and filtering tags are case insensitive\&.
.RE
.PP
\fB\-\-omit\-empty\fR
.RS 4
Do not print a newline after formatted refs where the format expands to the empty string\&.
.RE
.PP
\fB\-\-column\fR[\fB=\fR\fI<options>\fR], \fB\-\-no\-column\fR
.RS 4
Display tag listing in columns\&. See configuration variable
\fBcolumn\&.tag\fR
for option syntax\&.
\fB\-\-column\fR
and
\fB\-\-no\-column\fR
without options are equivalent to
\fBalways\fR
and
\fBnever\fR
respectively\&.
.sp
This option is only applicable when listing tags without annotation lines\&.
.RE
.PP
\fB\-\-contains\fR [\fI<commit>\fR]
.RS 4
Only list tags which contain
\fI<commit>\fR
(\fBHEAD\fR
if not specified)\&. Implies
\fB\-\-list\fR\&.
.RE
.PP
\fB\-\-no\-contains\fR [\fI<commit>\fR]
.RS 4
Only list tags which don\(cqt contain
\fI<commit>\fR
(\fBHEAD\fR
if not specified)\&. Implies
\fB\-\-list\fR\&.
.RE
.PP
\fB\-\-merged\fR [\fI<commit>\fR]
.RS 4
Only list tags whose commits are reachable from
\fI<commit>\fR
(\fBHEAD\fR
if not specified)\&.
.RE
.PP
\fB\-\-no\-merged\fR [\fI<commit>\fR]
.RS 4
Only list tags whose commits are not reachable from
\fI<commit>\fR
(\fBHEAD\fR
if not specified)\&.
.RE
.PP
\fB\-\-points\-at\fR [\fI<object>\fR]
.RS 4
Only list tags of
\fI<object>\fR
(\fBHEAD\fR
if not specified)\&. Implies
\fB\-\-list\fR\&.
.RE
.PP
\fB\-m\fR \fI<msg>\fR, \fB\-\-message=\fR\fI<msg>\fR
.RS 4
Use
\fI<msg>\fR
(instead of prompting)\&. If multiple
\fB\-m\fR
options are given, their values are concatenated as separate paragraphs\&. Implies
\fB\-a\fR
if none of
\fB\-a\fR,
\fB\-s\fR, or
\fB\-u\fR
\fI<key\-id>\fR
is given\&.
.RE
.PP
\fB\-F\fR \fI<file>\fR, \fB\-\-file=\fR\fI<file>\fR
.RS 4
Take the tag message from
\fI<file>\fR\&. Use
\fB\-\fR
to read the message from the standard input\&. Implies
\fB\-a\fR
if none of
\fB\-a\fR,
\fB\-s\fR, or
\fB\-u\fR
\fI<key\-id>\fR
is given\&.
.RE
.PP
\fB\-\-trailer\fR \fI<token>\fR[(\fB=\fR|\fB:\fR)\fI<value>\fR]
.RS 4
Specify a (\fI<token>\fR,
\fI<value>\fR) pair that should be applied as a trailer\&. (e\&.g\&.
\fBgit\fR
\fBtag\fR
\fB\-\-trailer\fR
"Custom\-Key:
\fBvalue\fR" will add a "Custom\-Key" trailer to the tag message\&.) The
\fBtrailer\&.*\fR
configuration variables (\fBgit-interpret-trailers\fR(1)) can be used to define if a duplicated trailer is omitted, where in the run of trailers each trailer would appear, and other details\&. The trailers can be extracted in
\fBgit\fR
\fBtag\fR
\fB\-\-list\fR, using
\fB\-\-format=\fR"%(\fBtrailers\fR)" placeholder\&.
.RE
.PP
\fB\-e\fR, \fB\-\-edit\fR
.RS 4
Let further edit the message taken from file with
\fB\-F\fR
and command line with
\fB\-m\fR\&.
.RE
.PP
\fB\-\-cleanup=\fR\fI<mode>\fR
.RS 4
Set how the tag message is cleaned up\&. The
\fI<mode>\fR
can be one of
\fBverbatim\fR,
\fBwhitespace\fR
and
\fBstrip\fR\&. The
\fBstrip\fR
mode is default\&. The
\fBverbatim\fR
mode does not change message at all,
\fBwhitespace\fR
removes just leading/trailing whitespace lines and
\fBstrip\fR
removes both whitespace and commentary\&.
.RE
.PP
\fB\-\-create\-reflog\fR
.RS 4
Create a reflog for the tag\&. To globally enable reflogs for tags, see
\fBcore\&.logAllRefUpdates\fR
in
\fBgit-config\fR(1)\&. The negated form
\fB\-\-no\-create\-reflog\fR
only overrides an earlier
\fB\-\-create\-reflog\fR, but currently does not negate the setting of
\fBcore\&.logAllRefUpdates\fR\&.
.RE
.PP
\fB\-\-format=\fR\fI<format>\fR
.RS 4
A string that interpolates
\fB%\fR(\fBfieldname\fR) from a tag ref being shown and the object it points at\&. The format is the same as that of
\fBgit-for-each-ref\fR(1)\&. When unspecified, defaults to
\fB%\fR(\fBrefname:strip=2\fR)\&.
.RE
.PP
\fI<tagname>\fR
.RS 4
The name of the tag to create, delete, or describe\&. The new tag name must pass all checks defined by
\fBgit-check-ref-format\fR(1)\&. Some of these checks may restrict the characters allowed in a tag name\&.
.RE
.PP
\fI<commit>\fR, \fI<object>\fR
.RS 4
The object that the new tag will refer to, usually a commit\&. Defaults to
\fBHEAD\fR\&.
.RE
.SH "CONFIGURATION"
.sp
By default, \fBgit\fR \fBtag\fR in sign\-with\-default mode (\fB\-s\fR) will use your committer identity (of the form \fBYour\fR \fBName\fR <your@email\&.\fBaddress\fR>) to find a key\&. If you want to use a different default key, you can specify it in the repository configuration as follows:
.sp
.if n \{\
.RS 4
.\}
.nf
[user]
    signingKey = <key\-id>
.fi
.if n \{\
.RE
.\}
.sp
The signing backend can be chosen via the \fBgpg\&.format\fR configuration variable, which defaults to \fBopenpgp\fR\&. See \fBgit-config\fR(1) for a list of other supported formats\&.
.sp
The path to the program used for each signing backend can be specified with the \fBgpg\&.\fR\fI<format>\fR\fB\&.program\fR configuration variable\&. For the \fBopenpgp\fR backend, \fBgpg\&.program\fR can be used as a synonym for \fBgpg\&.openpgp\&.program\fR\&. See \fBgit-config\fR(1) for details\&.
.sp
\fBpager\&.tag\fR is only respected when listing tags, i\&.e\&., when \fB\-l\fR is used or implied\&. The default is to use a pager\&.
.sp
See \fBgit-config\fR(1) for more details and other configuration variables\&.
.SH "DISCUSSION"
.SS "On Re\-tagging"
.sp
What should you do when you tag a wrong commit and you would want to re\-tag?
.sp
If you never pushed anything out, just re\-tag it\&. Use \fB\-f\fR to replace the old one\&. And you\(cqre done\&.
.sp
But if you have pushed things out (or others could just read your repository directly), then others will have already seen the old tag\&. In that case you can do one of two things:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  1." 4.2
.\}
The sane thing\&. Just admit you screwed up, and use a different name\&. Others have already seen one tag\-name, and if you keep the same name, you may be in the situation that two people both have "version X", but they actually have
\fIdifferent\fR
"X"\*(Aqs\&. So just call it "X\&.1" and be done with it\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.sp -1
.IP "  2." 4.2
.\}
The insane thing\&. You really want to call the new version "X" too,
\fIeven though\fR
others have already seen the old one\&. So just use
\fBgit\fR
\fBtag\fR
\fB\-f\fR
again, as if you hadn\(cqt already published the old one\&.
.RE
.sp
However, Git does \fBnot\fR (and it should not) change tags behind users back\&. So if somebody already got the old tag, doing a \fBgit\fR \fBpull\fR on your tree shouldn\(cqt just make them overwrite the old one\&.
.sp
If somebody got a release tag from you, you cannot just change the tag for them by updating your own one\&. This is a big security issue, in that people MUST be able to trust their tag\-names\&. If you really want to do the insane thing, you need to just fess up to it, and tell people that you messed up\&. You can do that by making a very public announcement saying:
.sp
.if n \{\
.RS 4
.\}
.nf
Ok, I messed up, and I pushed out an earlier version tagged as X\&. I
then fixed something, and retagged the *fixed* tree as X again\&.

If you got the wrong tag, and want the new one, please delete
the old one and fetch the new one by doing:

        git tag \-d X
        git fetch origin tag X

to get my updated tag\&.

You can test which tag you have by doing

        git rev\-parse X

which should return 0123456789abcdef\&.\&. if you have the new version\&.

Sorry for the inconvenience\&.
.fi
.if n \{\
.RE
.\}
.sp
Does this seem a bit complicated? It \fBshould\fR be\&. There is no way that it would be correct to just "fix" it automatically\&. People need to know that their tags might have been changed\&.
.SS "On Automatic following"
.sp
If you are following somebody else\(cqs tree, you are most likely using remote\-tracking branches (eg\&. \fBrefs/remotes/origin/master\fR)\&. You usually want the tags from the other end\&.
.sp
On the other hand, if you are fetching because you would want a one\-shot merge from somebody else, you typically do not want to get tags from there\&. This happens more often for people near the toplevel but not limited to them\&. Mere mortals when pulling from each other do not necessarily want to automatically get private anchor point tags from the other person\&.
.sp
Often, "please pull" messages on the mailing list just provide two pieces of information: a repo URL and a branch name; this is designed to be easily cut&pasted at the end of a \fBgit\fR \fBfetch\fR command line:
.sp
.if n \{\
.RS 4
.\}
.nf
Linus, please pull from

        git://git\&.\&.\&.\&./proj\&.git master

to get the following updates\&.\&.\&.
.fi
.if n \{\
.RE
.\}
.sp
becomes:
.sp
.if n \{\
.RS 4
.\}
.nf
$ git pull git://git\&.\&.\&.\&./proj\&.git master
.fi
.if n \{\
.RE
.\}
.sp
In such a case, you do not want to automatically follow the other person\(cqs tags\&.
.sp
One important aspect of Git is its distributed nature, which largely means there is no inherent "upstream" or "downstream" in the system\&. On the face of it, the above example might seem to indicate that the tag namespace is owned by the upper echelon of people and that tags only flow downwards, but that is not the case\&. It only shows that the usage pattern determines who are interested in whose tags\&.
.sp
A one\-shot pull is a sign that a commit history is now crossing the boundary between one circle of people (e\&.g\&. "people who are primarily interested in the networking part of the kernel") who may have their own set of tags (e\&.g\&. "this is the third release candidate from the networking group to be proposed for general consumption with 2\&.6\&.21 release") to another circle of people (e\&.g\&. "people who integrate various subsystem improvements")\&. The latter are usually not interested in the detailed tags used internally in the former group (that is what "internal" means)\&. That is why it is desirable not to follow tags automatically in this case\&.
.sp
It may well be that among networking people, they may want to exchange the tags internal to their group, but in that workflow they are most likely tracking each other\(cqs progress by having remote\-tracking branches\&. Again, the heuristic to automatically follow such tags is a good thing\&.
.SS "On Backdating Tags"
.sp
If you have imported some changes from another VCS and would like to add tags for major releases of your work, it is useful to be able to specify the date to embed inside of the tag object; such data in the tag object affects, for example, the ordering of tags in the gitweb interface\&.
.sp
To set the date used in future tag objects, set the environment variable GIT_COMMITTER_DATE (see the later discussion of possible values; the most common form is "YYYY\-MM\-DD HH:MM")\&.
.sp
For example:
.sp
.if n \{\
.RS 4
.\}
.nf
$ GIT_COMMITTER_DATE="2006\-10\-02 10:31" git tag \-s v1\&.0\&.1
.fi
.if n \{\
.RE
.\}
.SH "DATE FORMATS"
.sp
The \fBGIT_AUTHOR_DATE\fR and \fBGIT_COMMITTER_DATE\fR environment variables support the following date formats:
.PP
Git internal format
.RS 4
It is
\fI<unix\-timestamp>\fR
\fI<time\-zone\-offset>\fR, where
\fI<unix\-timestamp>\fR
is the number of seconds since the UNIX epoch\&.
\fI<time\-zone\-offset>\fR
is a positive or negative offset from UTC\&. For example CET (which is 1 hour ahead of UTC) is
\fB+0100\fR\&.
.RE
.PP
RFC 2822
.RS 4
The standard date format as described by RFC 2822, for example
\fBThu\fR,
\fB07\fR
\fBApr\fR
\fB2005\fR
\fB22:13:13\fR
\fB+0200\fR\&.
.RE
.PP
ISO 8601
.RS 4
Time and date specified by the ISO 8601 standard, for example
\fB2005\-04\-07T22:13:13\fR\&. The parser accepts a space instead of the
\fBT\fR
character as well\&. Fractional parts of a second will be ignored, for example
\fB2005\-04\-07T22:13:13\&.019\fR
will be treated as
\fB2005\-04\-07T22:13:13\fR\&.
.if n \{\
.sp
.\}
.RS 4
.it 1 an-trap
.nr an-no-space-flag 1
.nr an-break-flag 1
.br
.ps +1
\fBNote\fR
.ps -1
.br
In addition, the date part is accepted in the following formats:
\fBYYYY\&.MM\&.DD\fR,
\fBMM/DD/YYYY\fR
and
\fBDD\&.MM\&.YYYY\fR\&.
.sp .5v
.RE
.RE
.SH "FILES"
.PP
\fB$GIT_DIR/TAG_EDITMSG\fR
.RS 4
This file contains the message of an in\-progress annotated tag\&. If
\fBgit\fR
\fBtag\fR
exits due to an error before creating an annotated tag then the tag message that has been provided by the user in an editor session will be available in this file, but may be overwritten by the next invocation of
\fBgit\fR
\fBtag\fR\&.
.RE
.SH "CONFIGURATION"
.sp
Everything below this line in this section is selectively included from the \fBgit-config\fR(1) documentation\&. The content is the same as what\(cqs found there:
.PP
\fBtag\&.forceSignAnnotated\fR
.RS 4
A boolean to specify whether annotated tags created should be GPG signed\&. If
\fB\-\-annotate\fR
is specified on the command line, it takes precedence over this option\&.
.RE
.PP
\fBtag\&.sort\fR
.RS 4
This variable controls the sort ordering of tags when displayed by
\fBgit\-tag\fR\&. Without the
\fB\-\-sort=\fR\fI<value>\fR
option provided, the value of this variable will be used as the default\&.
.RE
.PP
\fBtag\&.gpgSign\fR
.RS 4
A boolean to specify whether all tags should be GPG signed\&. Use of this option when running in an automated script can result in a large number of tags being signed\&. It is therefore convenient to use an agent to avoid typing your GPG passphrase several times\&. Note that this option doesn\(cqt affect tag signing behavior enabled by
\fB\-u\fR
\fI<keyid>\fR
or
\fB\-\-local\-user=\fR\fI<keyid>\fR
options\&.
.RE
.SH "NOTES"
.sp
When combining multiple \fB\-\-contains\fR and \fB\-\-no\-contains\fR filters, only references that contain at least one of the \fB\-\-contains\fR commits and contain none of the \fB\-\-no\-contains\fR commits are shown\&.
.sp
When combining multiple \fB\-\-merged\fR and \fB\-\-no\-merged\fR filters, only references that are reachable from at least one of the \fB\-\-merged\fR commits and from none of the \fB\-\-no\-merged\fR commits are shown\&.
.SH "SEE ALSO"
.sp
\fBgit-check-ref-format\fR(1)\&. \fBgit-config\fR(1)\&.
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
