.\"     Title: git-unpack-file
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 07/01/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.2.rc0.64.ge9cc0
.\"
.TH "GIT\-UNPACK\-FILE" "1" "07/01/2009" "Git 1\.6\.2\.rc0\.64\.ge9cc0" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-unpack-file - Creates a temporary file with a blob's contents
.SH "SYNOPSIS"
\fIgit unpack\-file\fR <blob>
.sp
.SH "DESCRIPTION"
Creates a file holding the contents of the blob specified by sha1\. It returns the name of the temporary file in the following format: \.merge_file_XXXXX
.sp
.SH "OPTIONS"
.PP
<blob>
.RS 4
Must be a blob id
.RE
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl\.org>
.sp
.SH "DOCUMENTATION"
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger\.kernel\.org>\.
.sp
.SH "GIT"
Part of the \fBgit\fR(1) suite
.sp
