.\"     Title: git-check-attr
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 07/22/2008
.\"    Manual: Git Manual
.\"    Source: Git 1.6.0.rc0.14.g95f8
.\"
.TH "GIT\-CHECK\-ATTR" "1" "07/22/2008" "Git 1\.6\.0\.rc0\.14\.g95f8" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-check-attr - Display gitattributes information.
.SH "SYNOPSIS"
\fIgit check\-attr\fR attr\&... [\-\-] pathname\&...
.SH "DESCRIPTION"
For every pathname, this command will list if each attr is \fIunspecified\fR, \fIset\fR, or \fIunset\fR as a gitattribute on that pathname\.
.SH "OPTIONS"
.PP
\-\-
.RS 4
Interpret all preceding arguments as attributes, and all following arguments as path names\. If not supplied, only the first argument will be treated as an attribute\.
.RE
.SH "SEE ALSO"
\fBgitattributes\fR(5)\.
.SH "AUTHOR"
Written by Junio C Hamano <gitster@pobox\.com>
.SH "DOCUMENTATION"
Documentation by James Bowes\.
.SH "GIT"
Part of the \fBgit\fR(1) suite

