.\"     Title: git-cherry
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 07/22/2008
.\"    Manual: Git Manual
.\"    Source: Git 1.6.0.rc0.14.g95f8
.\"
.TH "GIT\-CHERRY" "1" "07/22/2008" "Git 1\.6\.0\.rc0\.14\.g95f8" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-cherry - Find commits not merged upstream
.SH "SYNOPSIS"
\fIgit cherry\fR [\-v] <upstream> [<head>] [<limit>]
.SH "DESCRIPTION"
The changeset (or "diff") of each commit between the fork\-point and <head> is compared against each commit between the fork\-point and <upstream>\. The commits are compared with their \fIpatch id\fR, obtained from the \fIgit\-patch\-id\fR program\.

Every commit that doesn\'t exist in the <upstream> branch has its id (sha1) reported, prefixed by a symbol\. The ones that have equivalent change already in the <upstream> branch are prefixed with a minus (\-) sign, and those that only exist in the <head> branch are prefixed with a plus (+) symbol:

.sp
.RS 4
.nf
           __*__*__*__*__> <upstream>
          /
fork\-point
          \e__+__+__\-__+__+__\-__+__> <head>
.fi
.RE
If a <limit> has been given then the commits along the <head> branch up to and including <limit> are not reported:

.sp
.RS 4
.nf
           __*__*__*__*__> <upstream>
          /
fork\-point
          \e__*__*__<limit>__\-__+__> <head>
.fi
.RE
Because \fIgit\-cherry\fR compares the changeset rather than the commit id (sha1), you can use \fIgit\-cherry\fR to find out if a commit you made locally has been applied <upstream> under a different commit id\. For example, this will happen if you\'re feeding patches <upstream> via email rather than pushing or pulling commits directly\.
.SH "OPTIONS"
.PP
\-v
.RS 4
Verbose\.
.RE
.PP
<upstream>
.RS 4
Upstream branch to compare against\.
.RE
.PP
<head>
.RS 4
Working branch; defaults to HEAD\.
.RE
.PP
<limit>
.RS 4
Do not report commits up to (and including) limit\.
.RE
.SH "SEE ALSO"
\fBgit-patch-id\fR(1)
.SH "AUTHOR"
Written by Junio C Hamano <gitster@pobox\.com>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano and the git\-list <git@vger\.kernel\.org>\.
.SH "GIT"
Part of the \fBgit\fR(1) suite

