.\"     Title: git-count-objects
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 09/19/2008
.\"    Manual: Git Manual
.\"    Source: Git 1.6.0.2.287.g3791f
.\"
.TH "GIT\-COUNT\-OBJECTS" "1" "09/19/2008" "Git 1\.6\.0\.2\.287\.g3791f" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-count-objects - Count unpacked number of objects and their disk consumption
.SH "SYNOPSIS"
\fIgit count\-objects\fR [\-v]
.SH "DESCRIPTION"
This counts the number of unpacked object files and disk space consumed by them, to help you decide when it is a good time to repack\.
.SH "OPTIONS"
.PP
\-v, \-\-verbose
.RS 4
In addition to the number of loose objects and disk space consumed, it reports the number of in\-pack objects, number of packs, disk space consumed by those packs, and number of objects that can be removed by running git prune\-packed\.
.RE
.SH "AUTHOR"
Written by Junio C Hamano <gitster@pobox\.com>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano and the git\-list <git@vger\.kernel\.org>\.
.SH "GIT"
Part of the \fBgit\fR(1) suite

