.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-HELP" "1" "03/15/2008" "Git 1.5.4.4.603.g1f9f" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-help \- display help information about git
.SH "SYNOPSIS"
\fIgit help\fR [\-a|\-\-all|\-i|\-\-info|\-m|\-\-man|\-w|\-\-web] [COMMAND]
.SH "DESCRIPTION"
With no options and no COMMAND given, the synopsis of the \fIgit\fR command and a list of the most commonly used git commands are printed on the standard output.

If the option \fI\-\-all\fR or \fI\-a\fR is given, then all available commands are printed on the standard output.

If a git command is named, a manual page for that command is brought up. The \fIman\fR program is used by default for this purpose, but this can be overridden by other options or configuration variables.

Note that \fIgit \-\-help \&...\fR is identical as \fIgit help \&...\fR because the former is internally converted into the latter.
.SH "OPTIONS"
.TP
\-a|\-\-all
Prints all the available commands on the standard output. This option supersedes any other option.
.TP
\-i|\-\-info
Display manual page for the command in the \fIinfo\fR format. The \fIinfo\fR program will be used for that purpose.
.TP
\-m|\-\-man
Display manual page for the command in the \fIman\fR format. This option may be used to override a value set in the \fIhelp.format\fR configuration variable.

By default the \fIman\fR program will be used to display the manual page, but the \fIman.viewer\fR configuration variable may be used to choose other display programs (see below).
.TP
\-w|\-\-web
Display manual page for the command in the \fIweb\fR (HTML) format. A web browser will be used for that purpose.

The web browser can be specified using the configuration variable \fIhelp.browser\fR, or \fIweb.browser\fR if the former is not set. If none of these config variables is set, the \fIgit\-web\-\-browse\fR helper script (called by \fIgit\-help\fR) will pick a suitable default. See \fBgit\-web\-\-browse\fR(1) for more information about this.
.SH "CONFIGURATION VARIABLES"
.SS "help.format"
If no command line option is passed, the \fIhelp.format\fR configuration variable will be checked. The following values are supported for this variable; they make \fIgit\-help\fR behave as their corresponding command line option:
.TP 3
\(bu
"man" corresponds to \fI\-m|\-\-man\fR,
.TP
\(bu
"info" corresponds to \fI\-i|\-\-info\fR,
.TP
\(bu
"web" or "html" correspond to \fI\-w|\-\-web\fR.
.SS "help.browser, web.browser and browser.<tool>.path"
The \fIhelp.browser\fR, \fIweb.browser\fR and \fIbrowser.<tool>.path\fR will also be checked if the \fIweb\fR format is chosen (either by command line option or configuration variable). See \fI\-w|\-\-web\fR in the OPTIONS section above and \fBgit\-web\-\-browse\fR(1).
.SS "man.viewer"
The \fIman.viewer\fR config variable will be checked if the \fIman\fR format is chosen. Only the following values are currently supported:
.TP 3
\(bu
"man": use the \fIman\fR program as usual,
.TP
\(bu
"woman": use \fIemacsclient\fR to launch the "woman" mode in emacs (this only works starting with emacsclient versions 22),
.TP
\(bu
"konqueror": use a man KIO slave in konqueror.

Multiple values may be given to this configuration variable. Their corresponding programs will be tried in the order listed in the configuration file.

For example, this configuration:
.sp
.nf
[man]
        viewer = konqueror
        viewer = woman
.fi
will try to use konqueror first. But this may fail (for example if DISPLAY is not set) and in that case emacs' woman mode will be tried.

If everything fails the \fIman\fR program will be tried anyway.
.SS "Note about git config \-\-global"
Note that all these configuration variables should probably be set using the \fI\-\-global\fR flag, for example like this:
.sp
.nf
.ft C
$ git config \-\-global help.format web
$ git config \-\-global web.browser firefox
.ft

.fi
as they are probably more user specific than repository specific. See \fBgit\-config\fR(1) for more information about this.
.SH "AUTHOR"
Written by Junio C Hamano <gitster@pobox.com> and the git\-list <git@vger.kernel.org>.
.SH "DOCUMENTATION"
Initial documentation was part of the \fBgit\fR(7) man page. Christian Couder <chriscool@tuxfamily.org> extracted and rewrote it a little. Maintenance is done by the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite

