'\" t
.\"     Title: git-version
.\"    Author: [FIXME: author] [see http://www.docbook.org/tdg5/en/html/author]
.\" Generator: DocBook XSL Stylesheets v1.79.2 <http://docbook.sf.net/>
.\"      Date: 2025-04-17
.\"    Manual: Git Manual
.\"    Source: Git 2.49.0.391.g4bbb303af6
.\"  Language: English
.\"
.TH "GIT\-VERSION" "1" "2025-04-17" "Git 2\&.49\&.0\&.391\&.g4bbb30" "Git Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-version \- Display version information about Git
.SH "SYNOPSIS"
.sp
.nf
\fIgit version\fR [\-\-build\-options]
.fi
.SH "DESCRIPTION"
.sp
With no options given, the version of \fIgit\fR is printed on the standard output\&.
.sp
Note that \fBgit\fR \fB\-\-version\fR is identical to \fBgit\fR \fBversion\fR because the former is internally converted into the latter\&.
.SH "OPTIONS"
.PP
\-\-build\-options
.RS 4
Include additional information about how git was built for diagnostic purposes\&.
.sp
The libraries used to implement the SHA\-1 and SHA\-256 algorithms are displayed in the form
\fBSHA\-1:\fR
\fI<option>\fR
and
\fBSHA\-256:\fR
\fI<option>\fR\&. Note that the SHA\-1 options
\fBSHA1_APPLE\fR,
\fBSHA1_OPENSSL\fR, and
\fBSHA1_BLK\fR
do not use a collision detection algorithm and thus may be vulnerable to known SHA\-1 collision attacks\&. When a faster SHA\-1 implementation without collision detection is used for only non\-cryptographic purposes, the algorithm is displayed in the form
\fBnon\-collision\-detecting\-SHA\-1:\fR
\fI<option>\fR\&.
.RE
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
