.\"     Title: git-pack-redundant
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 07/06/2008
.\"    Manual: Git Manual
.\"    Source: Git 1.5.6.2.212.g08b5
.\"
.TH "GIT\-PACK\-REDUNDANT" "1" "07/06/2008" "Git 1\.5\.6\.2\.212\.g08b5" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-pack-redundant - Find redundant pack files
.SH "SYNOPSIS"
\fIgit pack\-redundant\fR [ \-\-verbose ] [ \-\-alt\-odb ] < \-\-all | \.pack filename \&... >
.SH "DESCRIPTION"
This program computes which packs in your repository are redundant\. The output is suitable for piping to xargs rm if you are in the root of the repository\.

\fIgit\-pack\-redundant\fR accepts a list of objects on standard input\. Any objects given will be ignored when checking which packs are required\. This makes the following command useful when wanting to remove packs which contain unreachable objects\.

git fsck \-\-full \-\-unreachable | cut \-d \fI \fR \-f3 | git pack\-redundant \-\-all | xargs rm
.SH "OPTIONS"
.PP
\-\-all
.RS 4
Processes all packs\. Any filenames on the command line are ignored\.
.RE
.PP
\-\-alt\-odb
.RS 4
Don\'t require objects present in packs from alternate object directories to be present in local packs\.
.RE
.PP
\-\-verbose
.RS 4
Outputs some statistics to stderr\. Has a small performance penalty\.
.RE
.SH "AUTHOR"
Written by Lukas Sandstr\(:om <lukass@etek\.chalmers\.se>
.SH "DOCUMENTATION"
Documentation by Lukas Sandstr\(:om <lukass@etek\.chalmers\.se>
.SH "SEE ALSO"
\fBgit-pack-objects\fR(1) \fBgit-repack\fR(1) \fBgit-prune-packed\fR(1)
.SH "GIT"
Part of the \fBgit\fR(1) suite

