.\"     Title: git-verify-pack
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 10/31/2008
.\"    Manual: Git Manual
.\"    Source: Git 1.6.0.2.287.g3791f
.\"
.TH "GIT\-VERIFY\-PACK" "1" "10/31/2008" "Git 1\.6\.0\.2\.287\.g3791f" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-verify-pack - Validate packed git archive files
.SH "SYNOPSIS"
\fIgit verify\-pack\fR [\-v] [\-\-] <pack>\.idx \&...
.SH "DESCRIPTION"
Reads given idx file for packed git archive created with the \fIgit\-pack\-objects\fR command and verifies idx file and the corresponding pack file\.
.SH "OPTIONS"
.PP
<pack>\.idx \&...
.RS 4
The idx files to verify\.
.RE
.PP
\-v
.RS 4
After verifying the pack, show list of objects contained in the pack\.
.RE
.PP
\-\-
.RS 4
Do not interpret any more arguments as options\.
.RE
.SH "OUTPUT FORMAT"
When specifying the \-v option the format used is:

.sp
.RS 4
.nf
SHA1 type size size\-in\-pack\-file offset\-in\-packfile
.fi
.RE
for objects that are not deltified in the pack, and

.sp
.RS 4
.nf
SHA1 type size size\-in\-packfile offset\-in\-packfile depth base\-SHA1
.fi
.RE
for objects that are deltified\.
.SH "AUTHOR"
Written by Junio C Hamano <gitster@pobox\.com>
.SH "DOCUMENTATION"
Documentation by Junio C Hamano
.SH "GIT"
Part of the \fBgit\fR(1) suite

