.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-FETCH\-PACK" "1" "11/08/2006" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-fetch\-pack \- Receive missing objects from another repository
.SH "SYNOPSIS"
\fIgit\-fetch\-pack\fR [\-q] [\-k] [\-\-exec=<git\-upload\-pack>] [<host>:]<directory> [<refs>\&...]
.sp
.SH "DESCRIPTION"
Invokes \fIgit\-upload\-pack\fR on a potentially remote repository, and asks it to send objects missing from this repository, to update the named heads. The list of commits available locally is found out by scanning local $GIT_DIR/refs/ and sent to \fIgit\-upload\-pack\fR running on the other end.
.sp
This command degenerates to download everything to complete the asked refs from the remote side when the local side does not have a common ancestor commit.
.sp
.SH "OPTIONS"
.TP
\-q
Pass
\fI\-q\fR
flag to
\fIgit\-unpack\-objects\fR; this makes the cloning process less verbose.
.TP
\-k
Do not invoke
\fIgit\-unpack\-objects\fR
on received data, but create a single packfile out of it instead, and store it in the object database. If provided twice then the pack is locked against repacking.
.TP
\-\-exec=<git\-upload\-pack>
Use this to specify the path to
\fIgit\-upload\-pack\fR
on the remote side, if is not found on your $PATH. Installations of sshd ignores the user's environment setup scripts for login shells (e.g. .bash_profile) and your privately installed git may not be found on the system default $PATH. Another workaround suggested is to set up your $PATH in ".bashrc", but this flag is for people who do not want to pay the overhead for non\-interactive shells by having a lean .bashrc file (they set most of the things up in .bash_profile).
.TP
<host>
A remote host that houses the repository. When this part is specified,
\fIgit\-upload\-pack\fR
is invoked via ssh.
.TP
<directory>
The repository to sync from.
.TP
<refs>\&...
The remote heads to update from. This is relative to $GIT_DIR (e.g. "HEAD", "refs/heads/master"). When unspecified, update from all heads the remote side has.
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl.org>
.sp
.SH "DOCUMENTATION"
Documentation by Junio C Hamano.
.sp
.SH "GIT"
Part of the \fBgit\fR(7) suite
.sp
