'\" t
.\"     Title: git-show-index
.\"    Author: [see the "Author" section]
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 09/03/2010
.\"    Manual: Git Manual
.\"    Source: Git 1.7.2
.\"  Language: English
.\"
.TH "GIT\-SHOW\-INDEX" "1" "09/03/2010" "Git 1\&.7\&.2" "Git Manual"
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
git-show-index \- Show packed archive index
.SH "SYNOPSIS"
.sp
\fIgit show\-index\fR < idx\-file
.SH "DESCRIPTION"
.sp
Reads given idx file for packed git archive created with \fIgit pack\-objects\fR command, and dumps its contents\&.
.sp
The information it outputs is subset of what you can get from \fIgit verify\-pack \-v\fR; this command only shows the packfile offset and SHA1 of each object\&.
.SH "AUTHOR"
.sp
Written by Linus Torvalds <torvalds@osdl\&.org>
.SH "DOCUMENTATION"
.sp
Documentation by Junio C Hamano
.SH "GIT"
.sp
Part of the \fBgit\fR(1) suite
