.\"     Title: git-parse-remote
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 04/02/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.2.rc0.64.ge9cc0
.\"
.TH "GIT\-PARSE\-REMOTE" "1" "04/02/2009" "Git 1\.6\.2\.rc0\.64\.ge9cc0" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-parse-remote - Routines to help parsing remote repository access parameters
.SH "SYNOPSIS"
\fI\. "$(git \-\-exec\-path)/git\-parse\-remote"\fR
.sp
.SH "DESCRIPTION"
This script is included in various scripts to supply routines to parse files under $GIT_DIR/remotes/ and $GIT_DIR/branches/ and configuration variables that are related to fetching, pulling and pushing\.
.sp
The primary entry points are:
.PP
get_remote_refs_for_fetch
.RS 4
Given the list of user\-supplied
<repo> <refspec>\&..., return the list of refs to fetch after canonicalizing them into
$GIT_DIR
relative paths (e\.g\.
refs/heads/foo)\. When
<refspec>\&...
is empty the returned list of refs consists of the defaults for the given
<repo>, if specified in
$GIT_DIR/remotes/,
$GIT_DIR/branches/, or
remote\.*\.fetch
configuration\.
.RE
.PP
get_remote_refs_for_push
.RS 4
Given the list of user\-supplied
<repo> <refspec>\&..., return the list of refs to push in a form suitable to be fed to the
\fIgit\-send\-pack\fR
command\. When
<refspec>\&...
is empty the returned list of refs consists of the defaults for the given
<repo>, if specified in
$GIT_DIR/remotes/\.
.RE
.SH "AUTHOR"
Written by Junio C Hamano\.
.sp
.SH "DOCUMENTATION"
Documentation by Junio C Hamano and the git\-list <git@vger\.kernel\.org>\.
.sp
.SH "GIT"
Part of the \fBgit\fR(1) suite
.sp
