.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT\-SSH\-UPLOAD" "1" "07/19/2007" "Git 1.5.3.rc2.19.gc4fba" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git\-ssh\-upload \- Push to a remote repository over ssh connection
.SH "SYNOPSIS"
\fIgit\-ssh\-upload\fR [\-c] [\-t] [\-a] [\-d] [\-v] [\-w filename] [\-\-recover] commit\-id url
.SH "DESCRIPTION"
THIS COMMAND IS DEPRECATED.

Pushes from a remote repository over ssh connection, invoking git\-ssh\-fetch on the other end. It functions identically to git\-ssh\-fetch, aside from which end you run it on.
.SH "OPTIONS"
.TP
commit\-id
Id of commit to push.
.TP
\-c
Get the commit objects.
.TP
\-t
Get tree associated with the requested commit object.
.TP
\-a
Get all the objects.
.TP
\-v
Report what is uploaded.
.TP
\-w
Writes the commit\-id into the filename under [URL]/refs/ on the remote end after the transfer is complete.
.SH "AUTHOR"
Written by Daniel Barkalow <barkalow@iabervon.org>
.SH "DOCUMENTATION"
Documentation by Daniel Barkalow
.SH "GIT"
Part of the \fBgit\fR(7) suite

