.\"     Title: git-mv
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 07/01/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.2.rc0.64.ge9cc0
.\"
.TH "GIT\-MV" "1" "07/01/2009" "Git 1\.6\.2\.rc0\.64\.ge9cc0" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-mv - Move or rename a file, a directory, or a symlink
.SH "SYNOPSIS"
\fIgit mv\fR <options>\&... <args>\&...
.sp
.SH "DESCRIPTION"
This script is used to move or rename a file, directory or symlink\.
.sp
.sp
.RS 4
.nf
git mv [\-f] [\-n] <source> <destination>
git mv [\-f] [\-n] [\-k] <source> \.\.\. <destination directory>
.fi
.RE
In the first form, it renames <source>, which must exist and be either a file, symlink or directory, to <destination>\. In the second form, the last argument has to be an existing directory; the given sources will be moved into this directory\.
.sp
The index is updated after successful completion, but the change must still be committed\.
.sp
.SH "OPTIONS"
.PP
\-f
.RS 4
Force renaming or moving of a file even if the target exists
.RE
.PP
\-k
.RS 4
Skip move or rename actions which would lead to an error condition\. An error happens when a source is neither existing nor controlled by GIT, or when it would overwrite an existing file unless
\fI\-f\fR
is given\.
.RE
.PP
\-n, \-\-dry\-run
.RS 4
Do nothing; only show what would happen
.RE
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl\.org> Rewritten by Ryan Anderson <ryan@michonline\.com> Move functionality added by Josef Weidendorfer <Josef\.Weidendorfer@gmx\.de>
.sp
.SH "DOCUMENTATION"
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger\.kernel\.org>\.
.sp
.SH "GIT"
Part of the \fBgit\fR(1) suite
.sp
