.\"     Title: git-cat-file
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 05/26/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.3.1.169.g33fd
.\"
.TH "GIT\-CAT\-FILE" "1" "05/26/2009" "Git 1\.6\.3\.1\.169\.g33fd" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-cat-file - Provide content or type and size information for repository objects
.SH "SYNOPSIS"
.sp
.RS 4
.nf
\fIgit cat\-file\fR (\-t | \-s | \-e | \-p | <type>) <object>
\fIgit cat\-file\fR (\-\-batch | \-\-batch\-check) < <list\-of\-objects>
.fi
.RE
.SH "DESCRIPTION"
In its first form, the command provides the content or the type of an object in the repository\. The type is required unless \fI\-t\fR or \fI\-p\fR is used to find the object type, or \fI\-s\fR is used to find the object size\.
.sp
In the second form, a list of objects (separated by linefeeds) is provided on stdin, and the SHA1, type, and size of each object is printed on stdout\.
.sp
.SH "OPTIONS"
.PP
<object>
.RS 4
The name of the object to show\. For a more complete list of ways to spell object names, see the "SPECIFYING REVISIONS" section in
\fBgit-rev-parse\fR(1)\.
.RE
.PP
\-t
.RS 4
Instead of the content, show the object type identified by <object>\.
.RE
.PP
\-s
.RS 4
Instead of the content, show the object size identified by <object>\.
.RE
.PP
\-e
.RS 4
Suppress all output; instead exit with zero status if <object> exists and is a valid object\.
.RE
.PP
\-p
.RS 4
Pretty\-print the contents of <object> based on its type\.
.RE
.PP
<type>
.RS 4
Typically this matches the real type of <object> but asking for a type that can trivially be dereferenced from the given <object> is also permitted\. An example is to ask for a "tree" with <object> being a commit object that contains it, or to ask for a "blob" with <object> being a tag object that points at it\.
.RE
.PP
\-\-batch
.RS 4
Print the SHA1, type, size, and contents of each object provided on stdin\. May not be combined with any other options or arguments\.
.RE
.PP
\-\-batch\-check
.RS 4
Print the SHA1, type, and size of each object provided on stdin\. May not be combined with any other options or arguments\.
.RE
.SH "OUTPUT"
If \fI\-t\fR is specified, one of the <type>\.
.sp
If \fI\-s\fR is specified, the size of the <object> in bytes\.
.sp
If \fI\-e\fR is specified, no output\.
.sp
If \fI\-p\fR is specified, the contents of <object> are pretty\-printed\.
.sp
If <type> is specified, the raw (though uncompressed) contents of the <object> will be returned\.
.sp
If \fI\-\-batch\fR is specified, output of the following form is printed for each object specified on stdin:
.sp
.sp
.RS 4
.nf

\.ft C
<sha1> SP <type> SP <size> LF
<contents> LF
\.ft

.fi
.RE
If \fI\-\-batch\-check\fR is specified, output of the following form is printed for each object specified on stdin:
.sp
.sp
.RS 4
.nf

\.ft C
<sha1> SP <type> SP <size> LF
\.ft

.fi
.RE
For both \fI\-\-batch\fR and \fI\-\-batch\-check\fR, output of the following form is printed for each object specified on stdin that does not exist in the repository:
.sp
.sp
.RS 4
.nf

\.ft C
<object> SP missing LF
\.ft

.fi
.RE
.SH "AUTHOR"
Written by Linus Torvalds <torvalds@osdl\.org>
.sp
.SH "DOCUMENTATION"
Documentation by David Greaves, Junio C Hamano and the git\-list <git@vger\.kernel\.org>\.
.sp
.SH "GIT"
Part of the \fBgit\fR(1) suite
.sp
