.\"     Title: git-var
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 02/14/2009
.\"    Manual: Git Manual
.\"    Source: Git 1.6.2.rc0.64.ge9cc0
.\"
.TH "GIT\-VAR" "1" "02/14/2009" "Git 1\.6\.2\.rc0\.64\.ge9cc0" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git-var - Show a git logical variable
.SH "SYNOPSIS"
\fIgit var\fR [ \-l | <variable> ]
.SH "DESCRIPTION"
Prints a git logical variable\.
.SH "OPTIONS"
.PP
\-l
.RS 4
Cause the logical variables to be listed\. In addition, all the variables of the git configuration file \.git/config are listed as well\. (However, the configuration variables listing functionality is deprecated in favor of \fIgit config \-l\fR\.)
.RE
.SH "EXAMPLE"
.sp
.RS 4
.nf
$ git var GIT_AUTHOR_IDENT
Eric W\. Biederman <ebiederm@lnxi\.com> 1121223278 \-0600
.fi
.RE
.SH "VARIABLES"
.PP
GIT_AUTHOR_IDENT
.RS 4
The author of a piece of code\.
.RE
.PP
GIT_COMMITTER_IDENT
.RS 4
The person who put a piece of code into git\.
.RE
.SH "DIAGNOSTICS"
.PP
You don\'t exist\. Go away!
.RS 4
The passwd(5) gecos field couldn\'t be read
.RE
.PP
Your parents must have hated you!
.RS 4
The passwd(5) gecos field is longer than a giant static buffer\.
.RE
.PP
Your sysadmin must hate you!
.RS 4
The passwd(5) name field is longer than a giant static buffer\.
.RE
.SH "SEE ALSO"
\fBgit-commit-tree\fR(1) \fBgit-tag\fR(1) \fBgit-config\fR(1)
.SH "AUTHOR"
Written by Eric Biederman <ebiederm@xmission\.com>
.SH "DOCUMENTATION"
Documentation by Eric Biederman and the git\-list <git@vger\.kernel\.org>\.
.SH "GIT"
Part of the \fBgit\fR(1) suite

