.\" ** You probably do not want to edit this file directly **
.\" It was generated using the DocBook XSL Stylesheets (version 1.69.1).
.\" Instead of manually editing it, you probably should edit the DocBook XML
.\" source for it and then use the DocBook XSL Stylesheets to regenerate it.
.TH "GIT" "7" "04/21/2008" "Git 1.5.5.1.57.g5909c" "Git Manual"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
git \- the stupid content tracker
.SH "SYNOPSIS"
.sp
.nf
\fIgit\fR [\-\-version] [\-\-exec\-path[=GIT_EXEC_PATH]]
    [\-p|\-\-paginate|\-\-no\-pager]
    [\-\-bare] [\-\-git\-dir=GIT_DIR] [\-\-work\-tree=GIT_WORK_TREE]
    [\-\-help] COMMAND [ARGS]
.fi
.SH "DESCRIPTION"
Git is a fast, scalable, distributed revision control system with an unusually rich command set that provides both high\-level operations and full access to internals.

See this [1]\&\fItutorial\fR to get started, then see [2]\&\fIEveryday Git\fR for a useful minimum set of commands, and "man git\-commandname" for documentation of each command. CVS users may also want to read [3]\&\fICVS migration\fR. See [4]\&\fIGit User's Manual\fR for a more in\-depth introduction.

The COMMAND is either a name of a Git command (see below) or an alias as defined in the configuration file (see \fBgit\-config\fR(1)).

Formatted and hyperlinked version of the latest git documentation can be viewed at http://www.kernel.org/pub/software/scm/git/docs/.
.SH "OPTIONS"
.TP
\-\-version
Prints the git suite version that the \fIgit\fR program came from.
.TP
\-\-help
Prints the synopsis and a list of the most commonly used commands. If the option \fI\-\-all\fR or \fI\-a\fR is given then all available commands are printed. If a git command is named this option will bring up the manual page for that command.

Other options are available to control how the manual page is displayed. See \fBgit\-help\fR(1) for more information, because \fIgit \-\-help \&...\fR is converted internally into \fIgit help \&...\fR.
.TP
\-\-exec\-path
Path to wherever your core git programs are installed. This can also be controlled by setting the GIT_EXEC_PATH environment variable. If no path is given \fIgit\fR will print the current setting and then exit.
.TP
\-p|\-\-paginate
Pipe all output into \fIless\fR (or if set, $PAGER).
.TP
\-\-no\-pager
Do not pipe git output into a pager.
.TP
\-\-git\-dir=<path>
Set the path to the repository. This can also be controlled by setting the GIT_DIR environment variable.
.TP
\-\-work\-tree=<path>
Set the path to the working tree. The value will not be used in combination with repositories found automatically in a .git directory (i.e. $GIT_DIR is not set). This can also be controlled by setting the GIT_WORK_TREE environment variable and the core.worktree configuration variable.
.TP
\-\-bare
Treat the repository as a bare repository. If GIT_DIR environment is not set, it is set to the current working directory.
.SH "FURTHER DOCUMENTATION"
See the references above to get started using git. The following is probably more detail than necessary for a first\-time user.

The [5]\&\fIgit concepts chapter of the user\-manual\fR and the [6]\&\fICore tutorial\fR both provide introductions to the underlying git architecture.

See also the [7]\&\fIhowto\fR documents for some useful examples.

The internals are documented [8]\&\fIhere\fR.
.SH "GIT COMMANDS"
We divide git into high level ("porcelain") commands and low level ("plumbing") commands.
.SH "HIGH\-LEVEL COMMANDS (PORCELAIN)"
We separate the porcelain commands into the main commands and some ancillary user utilities.
.SS "Main porcelain commands"
.TP
\fBgit\-add\fR(1)
Add file contents to the index.
.TP
\fBgit\-am\fR(1)
Apply a series of patches from a mailbox.
.TP
\fBgit\-archive\fR(1)
Create an archive of files from a named tree.
.TP
\fBgit\-bisect\fR(1)
Find the change that introduced a bug by binary search.
.TP
\fBgit\-branch\fR(1)
List, create, or delete branches.
.TP
\fBgit\-bundle\fR(1)
Move objects and refs by archive.
.TP
\fBgit\-checkout\fR(1)
Checkout a branch or paths to the working tree.
.TP
\fBgit\-cherry\-pick\fR(1)
Apply the change introduced by an existing commit.
.TP
\fBgit\-citool\fR(1)
Graphical alternative to git\-commit.
.TP
\fBgit\-clean\fR(1)
Remove untracked files from the working tree.
.TP
\fBgit\-clone\fR(1)
Clone a repository into a new directory.
.TP
\fBgit\-commit\fR(1)
Record changes to the repository.
.TP
\fBgit\-describe\fR(1)
Show the most recent tag that is reachable from a commit.
.TP
\fBgit\-diff\fR(1)
Show changes between commits, commit and working tree, etc.
.TP
\fBgit\-fetch\fR(1)
Download objects and refs from another repository.
.TP
\fBgit\-format\-patch\fR(1)
Prepare patches for e\-mail submission.
.TP
\fBgit\-gc\fR(1)
Cleanup unnecessary files and optimize the local repository.
.TP
\fBgit\-grep\fR(1)
Print lines matching a pattern.
.TP
\fBgit\-gui\fR(1)
A portable graphical interface to Git.
.TP
\fBgit\-init\fR(1)
Create an empty git repository or reinitialize an existing one.
.TP
\fBgit\-log\fR(1)
Show commit logs.
.TP
\fBgit\-merge\fR(1)
Join two or more development histories together.
.TP
\fBgit\-mv\fR(1)
Move or rename a file, a directory, or a symlink.
.TP
\fBgit\-pull\fR(1)
Fetch from and merge with another repository or a local branch.
.TP
\fBgit\-push\fR(1)
Update remote refs along with associated objects.
.TP
\fBgit\-rebase\fR(1)
Forward\-port local commits to the updated upstream head.
.TP
\fBgit\-reset\fR(1)
Reset current HEAD to the specified state.
.TP
\fBgit\-revert\fR(1)
Revert an existing commit.
.TP
\fBgit\-rm\fR(1)
Remove files from the working tree and from the index.
.TP
\fBgit\-shortlog\fR(1)
Summarize \fIgit log\fR output.
.TP
\fBgit\-show\fR(1)
Show various types of objects.
.TP
\fBgit\-stash\fR(1)
Stash the changes in a dirty working directory away.
.TP
\fBgit\-status\fR(1)
Show the working tree status.
.TP
\fBgit\-submodule\fR(1)
Initialize, update or inspect submodules.
.TP
\fBgit\-tag\fR(1)
Create, list, delete or verify a tag object signed with GPG.
.TP
\fBgitk\fR(1)
The git repository browser.
.SS "Ancillary Commands"
Manipulators:
.TP
\fBgit\-config\fR(1)
Get and set repository or global options.
.TP
\fBgit\-fast\-export\fR(1)
Git data exporter.
.TP
\fBgit\-fast\-import\fR(1)
Backend for fast Git data importers.
.TP
\fBgit\-filter\-branch\fR(1)
Rewrite branches.
.TP
\fBgit\-lost\-found\fR(1)
(deprecated) Recover lost refs that luckily have not yet been pruned.
.TP
\fBgit\-mergetool\fR(1)
Run merge conflict resolution tools to resolve merge conflicts.
.TP
\fBgit\-pack\-refs\fR(1)
Pack heads and tags for efficient repository access.
.TP
\fBgit\-prune\fR(1)
Prune all unreachable objects from the object database.
.TP
\fBgit\-reflog\fR(1)
Manage reflog information.
.TP
\fBgit\-relink\fR(1)
Hardlink common objects in local repositories.
.TP
\fBgit\-remote\fR(1)
manage set of tracked repositories.
.TP
\fBgit\-repack\fR(1)
Pack unpacked objects in a repository.
.TP
\fBgit\-repo\-config\fR(1)
(deprecated) Get and set repository or global options.

Interrogators:
.TP
\fBgit\-annotate\fR(1)
Annotate file lines with commit info.
.TP
\fBgit\-blame\fR(1)
Show what revision and author last modified each line of a file.
.TP
\fBgit\-cherry\fR(1)
Find commits not merged upstream.
.TP
\fBgit\-count\-objects\fR(1)
Count unpacked number of objects and their disk consumption.
.TP
\fBgit\-fsck\fR(1)
Verifies the connectivity and validity of the objects in the database.
.TP
\fBgit\-get\-tar\-commit\-id\fR(1)
Extract commit ID from an archive created using git\-archive.
.TP
\fBgit\-help\fR(1)
display help information about git.
.TP
\fBgit\-instaweb\fR(1)
Instantly browse your working repository in gitweb.
.TP
\fBgit\-merge\-tree\fR(1)
Show three\-way merge without touching index.
.TP
\fBgit\-rerere\fR(1)
Reuse recorded resolution of conflicted merges.
.TP
\fBgit\-rev\-parse\fR(1)
Pick out and massage parameters.
.TP
\fBgit\-show\-branch\fR(1)
Show branches and their commits.
.TP
\fBgit\-verify\-tag\fR(1)
Check the GPG signature of tags.
.TP
\fBgit\-whatchanged\fR(1)
Show logs with difference each commit introduces.
.SS "Interacting with Others"
These commands are to interact with foreign SCM and with other people via patch over e\-mail.
.TP
\fBgit\-archimport\fR(1)
Import an Arch repository into git.
.TP
\fBgit\-cvsexportcommit\fR(1)
Export a single commit to a CVS checkout.
.TP
\fBgit\-cvsimport\fR(1)
Salvage your data out of another SCM people love to hate.
.TP
\fBgit\-cvsserver\fR(1)
A CVS server emulator for git.
.TP
\fBgit\-imap\-send\fR(1)
Dump a mailbox from stdin into an imap folder.
.TP
\fBgit\-quiltimport\fR(1)
Applies a quilt patchset onto the current branch.
.TP
\fBgit\-request\-pull\fR(1)
Generates a summary of pending changes.
.TP
\fBgit\-send\-email\fR(1)
Send a collection of patches as emails.
.TP
\fBgit\-svn\fR(1)
Bidirectional operation between a single Subversion branch and git.
.SH "LOW\-LEVEL COMMANDS (PLUMBING)"
Although git includes its own porcelain layer, its low\-level commands are sufficient to support development of alternative porcelains. Developers of such porcelains might start by reading about \fBgit\-update\-index\fR(1) and \fBgit\-read\-tree\fR(1).

The interface (input, output, set of options and the semantics) to these low\-level commands are meant to be a lot more stable than Porcelain level commands, because these commands are primarily for scripted use. The interface to Porcelain commands on the other hand are subject to change in order to improve the end user experience.

The following description divides the low\-level commands into commands that manipulate objects (in the repository, index, and working tree), commands that interrogate and compare objects, and commands that move objects and references between repositories.
.SS "Manipulation commands"
.TP
\fBgit\-apply\fR(1)
Apply a patch on a git index file and a working tree.
.TP
\fBgit\-checkout\-index\fR(1)
Copy files from the index to the working tree.
.TP
\fBgit\-commit\-tree\fR(1)
Create a new commit object.
.TP
\fBgit\-hash\-object\fR(1)
Compute object ID and optionally creates a blob from a file.
.TP
\fBgit\-index\-pack\fR(1)
Build pack index file for an existing packed archive.
.TP
\fBgit\-merge\-file\fR(1)
Run a three\-way file merge.
.TP
\fBgit\-merge\-index\fR(1)
Run a merge for files needing merging.
.TP
\fBgit\-mktag\fR(1)
Creates a tag object.
.TP
\fBgit\-mktree\fR(1)
Build a tree\-object from ls\-tree formatted text.
.TP
\fBgit\-pack\-objects\fR(1)
Create a packed archive of objects.
.TP
\fBgit\-prune\-packed\fR(1)
Remove extra objects that are already in pack files.
.TP
\fBgit\-read\-tree\fR(1)
Reads tree information into the index.
.TP
\fBgit\-symbolic\-ref\fR(1)
Read and modify symbolic refs.
.TP
\fBgit\-unpack\-objects\fR(1)
Unpack objects from a packed archive.
.TP
\fBgit\-update\-index\fR(1)
Register file contents in the working tree to the index.
.TP
\fBgit\-update\-ref\fR(1)
Update the object name stored in a ref safely.
.TP
\fBgit\-write\-tree\fR(1)
Create a tree object from the current index.
.SS "Interrogation commands"
.TP
\fBgit\-cat\-file\fR(1)
Provide content or type/size information for repository objects.
.TP
\fBgit\-diff\-files\fR(1)
Compares files in the working tree and the index.
.TP
\fBgit\-diff\-index\fR(1)
Compares content and mode of blobs between the index and repository.
.TP
\fBgit\-diff\-tree\fR(1)
Compares the content and mode of blobs found via two tree objects.
.TP
\fBgit\-for\-each\-ref\fR(1)
Output information on each ref.
.TP
\fBgit\-ls\-files\fR(1)
Show information about files in the index and the working tree.
.TP
\fBgit\-ls\-remote\fR(1)
List references in a remote repository.
.TP
\fBgit\-ls\-tree\fR(1)
List the contents of a tree object.
.TP
\fBgit\-merge\-base\fR(1)
Find as good common ancestors as possible for a merge.
.TP
\fBgit\-name\-rev\fR(1)
Find symbolic names for given revs.
.TP
\fBgit\-pack\-redundant\fR(1)
Find redundant pack files.
.TP
\fBgit\-rev\-list\fR(1)
Lists commit objects in reverse chronological order.
.TP
\fBgit\-show\-index\fR(1)
Show packed archive index.
.TP
\fBgit\-show\-ref\fR(1)
List references in a local repository.
.TP
\fBgit\-tar\-tree\fR(1)
(deprecated) Create a tar archive of the files in the named tree object.
.TP
\fBgit\-unpack\-file\fR(1)
Creates a temporary file with a blob's contents.
.TP
\fBgit\-var\fR(1)
Show a git logical variable.
.TP
\fBgit\-verify\-pack\fR(1)
Validate packed git archive files.

In general, the interrogate commands do not touch the files in the working tree.
.SS "Synching repositories"
.TP
\fBgit\-daemon\fR(1)
A really simple server for git repositories.
.TP
\fBgit\-fetch\-pack\fR(1)
Receive missing objects from another repository.
.TP
\fBgit\-send\-pack\fR(1)
Push objects over git protocol to another repository.
.TP
\fBgit\-update\-server\-info\fR(1)
Update auxiliary info file to help dumb servers.

The following are helper programs used by the above; end users typically do not use them directly.
.TP
\fBgit\-http\-fetch\fR(1)
Download from a remote git repository via HTTP.
.TP
\fBgit\-http\-push\fR(1)
Push objects over HTTP/DAV to another repository.
.TP
\fBgit\-parse\-remote\fR(1)
Routines to help parsing remote repository access parameters.
.TP
\fBgit\-receive\-pack\fR(1)
Receive what is pushed into the repository.
.TP
\fBgit\-shell\fR(1)
Restricted login shell for GIT\-only SSH access.
.TP
\fBgit\-upload\-archive\fR(1)
Send archive back to git\-archive.
.TP
\fBgit\-upload\-pack\fR(1)
Send objects packed back to git\-fetch\-pack.
.SS "Internal helper commands"
These are internal helper commands used by other commands; end users typically do not use them directly.
.TP
\fBgit\-check\-attr\fR(1)
Display gitattributes information..
.TP
\fBgit\-check\-ref\-format\fR(1)
Make sure ref name is well formed.
.TP
\fBgit\-fmt\-merge\-msg\fR(1)
Produce a merge commit message.
.TP
\fBgit\-mailinfo\fR(1)
Extracts patch and authorship from a single e\-mail message.
.TP
\fBgit\-mailsplit\fR(1)
Simple UNIX mbox splitter program.
.TP
\fBgit\-merge\-one\-file\fR(1)
The standard helper program to use with git\-merge\-index.
.TP
\fBgit\-patch\-id\fR(1)
Compute unique ID for a patch.
.TP
\fBgit\-peek\-remote\fR(1)
(deprecated) List the references in a remote repository.
.TP
\fBgit\-sh\-setup\fR(1)
Common git shell script setup code.
.TP
\fBgit\-stripspace\fR(1)
Filter out empty lines.
.SH "CONFIGURATION MECHANISM"
Starting from 0.99.9 (actually mid 0.99.8.GIT), .git/config file is used to hold per\-repository configuration options. It is a simple text file modeled after .ini format familiar to some people. Here is an example:
.sp
.nf
.ft C
#
# A '#' or ';' character indicates a comment.
#

; core variables
[core]
        ; Don't trust file modes
        filemode = false

; user identity
[user]
        name = "Junio C Hamano"
        email = "junkio@twinsun.com"
.ft

.fi
Various commands read from the configuration file and adjust their operation accordingly.
.SH "IDENTIFIER TERMINOLOGY"
.TP
<object>
Indicates the object name for any type of object.
.TP
<blob>
Indicates a blob object name.
.TP
<tree>
Indicates a tree object name.
.TP
<commit>
Indicates a commit object name.
.TP
<tree\-ish>
Indicates a tree, commit or tag object name. A command that takes a <tree\-ish> argument ultimately wants to operate on a <tree> object but automatically dereferences <commit> and <tag> objects that point at a <tree>.
.TP
<commit\-ish>
Indicates a commit or tag object name. A command that takes a <commit\-ish> argument ultimately wants to operate on a <commit> object but automatically dereferences <tag> objects that point at a <commit>.
.TP
<type>
Indicates that an object type is required. Currently one of: blob, tree, commit, or tag.
.TP
<file>
Indicates a filename \- almost always relative to the root of the tree structure GIT_INDEX_FILE describes.
.SH "SYMBOLIC IDENTIFIERS"
Any git command accepting any <object> can also use the following symbolic notation:
.TP
HEAD
indicates the head of the current branch (i.e. the contents of $GIT_DIR/HEAD).
.TP
<tag>
a valid tag \fIname\fR (i.e. the contents of $GIT_DIR/refs/tags/<tag>).
.TP
<head>
a valid head \fIname\fR (i.e. the contents of $GIT_DIR/refs/heads/<head>).

For a more complete list of ways to spell object names, see "SPECIFYING REVISIONS" section in \fBgit\-rev\-parse\fR(1).
.SH "FILE/DIRECTORY STRUCTURE"
Please see the [9]\&\fIrepository layout\fR document.

Read [10]\&\fIhooks\fR for more details about each hook.

Higher level SCMs may provide and manage additional information in the $GIT_DIR.
.SH "TERMINOLOGY"
Please see the [11]\&\fIglossary\fR document.
.SH "ENVIRONMENT VARIABLES"
Various git commands use the following environment variables:
.SS "The git Repository"
These environment variables apply to \fIall\fR core git commands. Nb: it is worth noting that they may be used/overridden by SCMS sitting above git so take care if using Cogito etc.
.TP
\fIGIT_INDEX_FILE\fR
This environment allows the specification of an alternate index file. If not specified, the default of $GIT_DIR/index is used.
.TP
\fIGIT_OBJECT_DIRECTORY\fR
If the object storage directory is specified via this environment variable then the sha1 directories are created underneath \- otherwise the default $GIT_DIR/objects directory is used.
.TP
\fIGIT_ALTERNATE_OBJECT_DIRECTORIES\fR
Due to the immutable nature of git objects, old objects can be archived into shared, read\-only directories. This variable specifies a ":" separated list of git object directories which can be used to search for git objects. New objects will not be written to these directories.
.TP
\fIGIT_DIR\fR
If the \fIGIT_DIR\fR environment variable is set then it specifies a path to use instead of the default .git for the base of the repository.
.TP
\fIGIT_WORK_TREE\fR
Set the path to the working tree. The value will not be used in combination with repositories found automatically in a .git directory (i.e. $GIT_DIR is not set). This can also be controlled by the \fI\-\-work\-tree\fR command line option and the core.worktree configuration variable.
.SS "git Commits"
.TP
\fIGIT_AUTHOR_NAME\fR , \fIGIT_AUTHOR_EMAIL\fR , \fIGIT_AUTHOR_DATE\fR , \fIGIT_COMMITTER_NAME\fR , \fIGIT_COMMITTER_EMAIL\fR , \fIGIT_COMMITTER_DATE\fR , \fIEMAIL\fR
see \fBgit\-commit\-tree\fR(1)
.SS "git Diffs"
.TP
\fIGIT_DIFF_OPTS\fR
Only valid setting is "\-\-unified=??" or "\-u??" to set the number of context lines shown when a unified diff is created. This takes precedence over any "\-U" or "\-\-unified" option value passed on the git diff command line.
.TP
\fIGIT_EXTERNAL_DIFF\fR
When the environment variable \fIGIT_EXTERNAL_DIFF\fR is set, the program named by it is called, instead of the diff invocation described above. For a path that is added, removed, or modified, \fIGIT_EXTERNAL_DIFF\fR is called with 7 parameters:
.sp
.nf
path old\-file old\-hex old\-mode new\-file new\-hex new\-mode
.fi
where:

<old|new>\-file


are files GIT_EXTERNAL_DIFF can use to read the contents of <old|new>,


<old|new>\-hex


are the 40\-hexdigit SHA1 hashes,


<old|new>\-mode


are the octal representation of the file modes.


The file parameters can point at the user's working file (e.g. new\-file in "git\-diff\-files"), /dev/null (e.g. old\-file when a new file is added), or a temporary file (e.g. old\-file in the index). \fIGIT_EXTERNAL_DIFF\fR should not worry about unlinking the temporary file \-\-\- it is removed when \fIGIT_EXTERNAL_DIFF\fR exits.

For a path that is unmerged, \fIGIT_EXTERNAL_DIFF\fR is called with 1 parameter, <path>.
.SS "other"
.TP
\fIGIT_MERGE_VERBOSITY\fR
A number controlling the amount of output shown by the recursive merge strategy. Overrides merge.verbosity. See \fBgit\-merge\fR(1)
.TP
\fIGIT_PAGER\fR
This environment variable overrides $PAGER. If it is set to an empty string or to the value "cat", git will not launch a pager.
.TP
\fIGIT_SSH\fR
If this environment variable is set then \fBgit\-fetch\fR(1) and \fBgit\-push\fR(1) will use this command instead of ssh when they need to connect to a remote system. The \fIGIT_SSH\fR command will be given exactly two arguments: the \fIusername@host\fR (or just \fIhost\fR) from the URL and the shell command to execute on that remote system.

To pass options to the program that you want to list in GIT_SSH you will need to wrap the program and options into a shell script, then set GIT_SSH to refer to the shell script.

Usually it is easier to configure any desired options through your personal .ssh/config file. Please consult your ssh documentation for further details.
.TP
\fIGIT_FLUSH\fR
If this environment variable is set to "1", then commands such as git\-blame (in incremental mode), git\-rev\-list, git\-log, git\-whatchanged, etc., will force a flush of the output stream after each commit\-oriented record have been flushed. If this variable is set to "0", the output of these commands will be done using completely buffered I/O. If this environment variable is not set, git will choose buffered or record\-oriented flushing based on whether stdout appears to be redirected to a file or not.
.TP
\fIGIT_TRACE\fR
If this variable is set to "1", "2" or "true" (comparison is case insensitive), git will print trace: messages on stderr telling about alias expansion, built\-in command execution and external command execution. If this variable is set to an integer value greater than 1 and lower than 10 (strictly) then git will interpret this value as an open file descriptor and will try to write the trace messages into this file descriptor. Alternatively, if this variable is set to an absolute path (starting with a \fI/\fR character), git will interpret this as a file path and will try to write the trace messages into it.
.SH "DISCUSSION"
More detail on the following is available from the [5]\&\fIgit concepts chapter of the user\-manual\fR and the [6]\&\fICore tutorial\fR.

A git project normally consists of a working directory with a ".git" subdirectory at the top level. The .git directory contains, among other things, a compressed object database representing the complete history of the project, an "index" file which links that history to the current contents of the working tree, and named pointers into that history such as tags and branch heads.

The object database contains objects of three main types: blobs, which hold file data; trees, which point to blobs and other trees to build up directory hierarchies; and commits, which each reference a single tree and some number of parent commits.

The commit, equivalent to what other systems call a "changeset" or "version", represents a step in the project's history, and each parent represents an immediately preceding step. Commits with more than one parent represent merges of independent lines of development.

All objects are named by the SHA1 hash of their contents, normally written as a string of 40 hex digits. Such names are globally unique. The entire history leading up to a commit can be vouched for by signing just that commit. A fourth object type, the tag, is provided for this purpose.

When first created, objects are stored in individual files, but for efficiency may later be compressed together into "pack files".

Named pointers called refs mark interesting points in history. A ref may contain the SHA1 name of an object or the name of another ref. Refs with names beginning ref/head/ contain the SHA1 name of the most recent commit (or "head") of a branch under development. SHA1 names of tags of interest are stored under ref/tags/. A special ref named HEAD contains the name of the currently checked\-out branch.

The index file is initialized with a list of all paths and, for each path, a blob object and a set of attributes. The blob object represents the contents of the file as of the head of the current branch. The attributes (last modified time, size, etc.) are taken from the corresponding file in the working tree. Subsequent changes to the working tree can be found by comparing these attributes. The index may be updated with new content, and new commits may be created from the content stored in the index.

The index is also capable of storing multiple entries (called "stages") for a given pathname. These stages are used to hold the various unmerged version of a file when a merge is in progress.
.SH "AUTHORS"
.TP 3
\(bu
git's founding father is Linus Torvalds <torvalds@osdl.org>.
.TP
\(bu
The current git nurse is Junio C Hamano <gitster@pobox.com>.
.TP
\(bu
The git potty was written by Andreas Ericsson <ae@op5.se>.
.TP
\(bu
General upbringing is handled by the git\-list <git@vger.kernel.org>.
.SH "DOCUMENTATION"
The documentation for git suite was started by David Greaves <david@dgreaves.com>, and later enhanced greatly by the contributors on the git\-list <git@vger.kernel.org>.
.SH "GIT"
Part of the \fBgit\fR(7) suite
.SH "REFERENCES"
.TP 4
 1.\ tutorial
\%tutorial.html
.TP 4
 2.\ Everyday Git
\%everyday.html
.TP 4
 3.\ CVS migration
\%cvs\-migration.html
.TP 4
 4.\ Git User's Manual
\%user\-manual.html
.TP 4
 5.\ git concepts chapter of the user\-manual
\%user\-manual.html#git\-concepts
.TP 4
 6.\ Core tutorial
\%core\-tutorial.html
.TP 4
 7.\ howto
\%howto\-index.html
.TP 4
 8.\ here
\%technical/api\-index.html
.TP 4
 9.\ repository layout
\%repository\-layout.html
.TP 4
10.\ hooks
\%hooks.html
.TP 4
11.\ glossary
\%glossary.html
